ALTER TABLE edges ADD COLUMN IF NOT EXISTS source_port TEXT NOT NULL DEFAULT 'auto';
ALTER TABLE edges ADD COLUMN IF NOT EXISTS target_port TEXT NOT NULL DEFAULT 'auto';
ALTER TABLE edges ADD COLUMN IF NOT EXISTS waypoints JSONB NOT NULL DEFAULT '[]';
