package output

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"time"
)

// graphNode is the local representation of a node from the API response.
type graphNode struct {
	ID          string   `json:"id"`
	Type        string   `json:"type"`
	Title       string   `json:"title"`
	Description *string  `json:"description"`
	Status      string   `json:"status"`
	Tags         []string `json:"tags"`
	ParentID     *string  `json:"parentId"`
	CreatedAt    string   `json:"createdAt"`
	CreatorEmail string   `json:"creatorEmail"`
}

// graphEdge is the local representation of an edge from the API response.
type graphEdge struct {
	ID       string  `json:"id"`
	SourceID string  `json:"sourceId"`
	TargetID string  `json:"targetId"`
	EdgeType string  `json:"edgeType"`
	Label    *string `json:"label"`
}

// graphData is the shape of the API response data field.
type graphData struct {
	Nodes []graphNode `json:"nodes"`
	Edges []graphEdge `json:"edges"`
}

var (
	nonAlnum   = regexp.MustCompile(`[^a-z0-9]+`)
	multiHyph  = regexp.MustCompile(`-{2,}`)
)

// slugify converts a title to a GitHub-style anchor slug. Returns "" if the
// title has no [a-z0-9] characters (e.g. all-Unicode, emoji-only, punctuation).
func slugify(title string) string {
	s := strings.ToLower(title)
	s = nonAlnum.ReplaceAllString(s, "-")
	s = multiHyph.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	return s
}

// buildAnchorMap returns nodeID -> stable anchor slug, guaranteeing
// (a) non-empty (falls back to "node-<id-prefix>") and
// (b) uniqueness across the document (appends -1, -2, ... on collisions).
func buildAnchorMap(nodes []graphNode) map[string]string {
	out := make(map[string]string, len(nodes))
	seen := make(map[string]int)
	for _, n := range nodes {
		base := slugify(n.Title)
		if base == "" {
			short := n.ID
			if len(short) > 8 {
				short = short[:8]
			}
			base = "node-" + short
		}
		anchor := base
		if c, ok := seen[base]; ok {
			anchor = fmt.Sprintf("%s-%d", base, c+1)
			seen[base] = c + 1
		} else {
			seen[base] = 0
		}
		out[n.ID] = anchor
	}
	return out
}

// RenderGraphAsMarkdown renders raw graph JSON (as returned by /api/projects/:id/graph)
// into a human-readable markdown handoff document.
func RenderGraphAsMarkdown(rawJSON []byte, projectName string, now time.Time) (string, error) {
	// Unwrap { "data": { "nodes": [...], "edges": [...] } } or bare { "nodes": [...], "edges": [...] }
	var envelope struct {
		Data *graphData `json:"data"`
	}
	if err := json.Unmarshal(rawJSON, &envelope); err != nil {
		return "", fmt.Errorf("failed to parse graph JSON: %w", err)
	}

	var g graphData
	if envelope.Data != nil {
		g = *envelope.Data
	} else {
		if err := json.Unmarshal(rawJSON, &g); err != nil {
			return "", fmt.Errorf("failed to parse graph JSON: %w", err)
		}
	}

	// Sort nodes: createdAt ascending, then title for ties.
	sort.Slice(g.Nodes, func(i, j int) bool {
		if g.Nodes[i].CreatedAt != g.Nodes[j].CreatedAt {
			return g.Nodes[i].CreatedAt < g.Nodes[j].CreatedAt
		}
		return g.Nodes[i].Title < g.Nodes[j].Title
	})

	// Build lookup maps.
	nodeByID := make(map[string]graphNode, len(g.Nodes))
	for _, n := range g.Nodes {
		nodeByID[n.ID] = n
	}
	// Pre-compute stable, unique anchor slugs per node ID so cross-links never
	// collide or point at empty anchors (Unicode/emoji-only titles).
	anchors := buildAnchorMap(g.Nodes)

	// For each node, collect depends_on targets and blocks targets.
	dependsOn := make(map[string][]string) // nodeID -> []targetID
	blocks := make(map[string][]string)    // nodeID -> []targetID
	children := make(map[string][]string) // parentID -> []childID

	for _, e := range g.Edges {
		switch e.EdgeType {
		case "depends_on":
			dependsOn[e.SourceID] = append(dependsOn[e.SourceID], e.TargetID)
		case "blocks":
			blocks[e.SourceID] = append(blocks[e.SourceID], e.TargetID)
		}
	}
	for _, n := range g.Nodes {
		if n.ParentID != nil && *n.ParentID != "" {
			children[*n.ParentID] = append(children[*n.ParentID], n.ID)
		}
	}

	var sb strings.Builder

	// Document header.
	fmt.Fprintf(&sb, "# %s\n\n", projectName)
	fmt.Fprintf(&sb, "Generated by `thask graph export --format md` on %s.\n\n", now.Format("2006-01-02"))
	fmt.Fprintf(&sb, "---\n\n")

	if len(g.Nodes) == 0 {
		sb.WriteString("_No nodes in this graph._\n")
		return sb.String(), nil
	}

	for _, n := range g.Nodes {
		fmt.Fprintf(&sb, "<a id=\"%s\"></a>\n\n## %s\n\n", anchors[n.ID], n.Title)

		// Badge line.
		badge := fmt.Sprintf("`%s` · `%s`", n.Type, n.Status)
		if len(n.Tags) > 0 {
			tagParts := make([]string, len(n.Tags))
			for i, t := range n.Tags {
				tagParts[i] = "`" + t + "`"
			}
			badge += " · tags: " + strings.Join(tagParts, ", ")
		}
		fmt.Fprintf(&sb, "%s\n\n", badge)

		// Description.
		if n.Description != nil && *n.Description != "" {
			fmt.Fprintf(&sb, "%s\n\n", *n.Description)
		}

		// GROUP children summary.
		if n.Type == "GROUP" {
			if kids, ok := children[n.ID]; ok && len(kids) > 0 {
				sb.WriteString("**Children:**\n\n")
				for _, cid := range kids {
					if child, ok := nodeByID[cid]; ok {
						fmt.Fprintf(&sb, "- [%s](#%s)\n", child.Title, anchors[child.ID])
					}
				}
				sb.WriteString("\n")
			}
		}

		// Depends on.
		if deps, ok := dependsOn[n.ID]; ok && len(deps) > 0 {
			sb.WriteString("### Depends on\n\n")
			for _, tid := range deps {
				if target, ok := nodeByID[tid]; ok {
					fmt.Fprintf(&sb, "- [%s](#%s)\n", target.Title, anchors[target.ID])
				}
			}
			sb.WriteString("\n")
		}

		// Blocks.
		if blks, ok := blocks[n.ID]; ok && len(blks) > 0 {
			sb.WriteString("### Blocks\n\n")
			for _, tid := range blks {
				if target, ok := nodeByID[tid]; ok {
					fmt.Fprintf(&sb, "- [%s](#%s)\n", target.Title, anchors[target.ID])
				}
			}
			sb.WriteString("\n")
		}

		// Creator footer.
		createdAt := n.CreatedAt
		if t, err := time.Parse(time.RFC3339Nano, n.CreatedAt); err == nil {
			createdAt = t.Format("2006-01-02")
		}
		if n.CreatorEmail != "" {
			fmt.Fprintf(&sb, "> Created by %s · %s\n\n", n.CreatorEmail, createdAt)
		} else {
			fmt.Fprintf(&sb, "> Created · %s\n\n", createdAt)
		}

		sb.WriteString("---\n\n")
	}

	return sb.String(), nil
}
