package output

import (
	"encoding/json"
	"strings"
	"testing"
	"time"
)

func TestRenderGraphAsMarkdown_HappyPath(t *testing.T) {
	desc1 := "Handles authentication flow for all API endpoints."
	desc2 := "Depends on auth service being complete before work can begin."

	nodes := []graphNode{
		{
			ID:          "node-1",
			Type:        "TASK",
			Title:       "Auth Service",
			Description: &desc1,
			Status:      "PASS",
			Tags:        []string{"backend", "security"},
			CreatedAt:   "2026-01-15T00:00:00Z",
		},
		{
			ID:          "node-2",
			Type:        "TASK",
			Title:       "API Gateway",
			Description: &desc2,
			Status:      "IN_PROGRESS",
			Tags:        []string{},
			CreatedAt:   "2026-01-15T01:00:00Z",
		},
		{
			ID:        "node-3",
			Type:      "MILESTONE",
			Title:     "v1 Launch",
			Status:    "TODO",
			Tags:      []string{"release"},
			CreatedAt: "2026-01-15T02:00:00Z",
		},
	}

	edges := []graphEdge{
		{
			ID:       "edge-1",
			SourceID: "node-2",
			TargetID: "node-1",
			EdgeType: "depends_on",
		},
		{
			ID:       "edge-2",
			SourceID: "node-1",
			TargetID: "node-3",
			EdgeType: "blocks",
		},
	}

	raw, err := json.Marshal(map[string]any{
		"data": map[string]any{
			"nodes": nodes,
			"edges": edges,
		},
	})
	if err != nil {
		t.Fatal(err)
	}

	now := time.Date(2026, 1, 15, 0, 0, 0, 0, time.UTC)
	result, err := RenderGraphAsMarkdown(raw, "My Project", now)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	checks := []string{
		"# My Project",
		"Generated by `thask graph export --format md` on 2026-01-15",
		"## Auth Service",
		"`TASK` · `PASS` · tags: `backend`, `security`",
		"Handles authentication flow for all API endpoints.",
		"### Blocks",
		"[v1 Launch](#v1-launch)",
		"## API Gateway",
		"`TASK` · `IN_PROGRESS`",
		"### Depends on",
		"[Auth Service](#auth-service)",
		"## v1 Launch",
		"`MILESTONE` · `TODO` · tags: `release`",
		"> Created · 2026-01-15",
	}

	for _, want := range checks {
		if !strings.Contains(result, want) {
			t.Errorf("expected output to contain %q\n\nFull output:\n%s", want, result)
		}
	}
}

func TestRenderGraphAsMarkdown_EmptyGraph(t *testing.T) {
	raw, _ := json.Marshal(map[string]any{
		"data": map[string]any{
			"nodes": []any{},
			"edges": []any{},
		},
	})

	now := time.Date(2026, 1, 15, 0, 0, 0, 0, time.UTC)
	result, err := RenderGraphAsMarkdown(raw, "Empty Project", now)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if !strings.Contains(result, "# Empty Project") {
		t.Errorf("expected header, got: %s", result)
	}
	if !strings.Contains(result, "_No nodes in this graph._") {
		t.Errorf("expected empty message, got: %s", result)
	}
}
