// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_key.sql

package dbgen

import (
	"context"
	"time"

	model "github.com/thask/backend/internal/model"
)

const aPIKeyCountByUserID = `-- name: APIKeyCountByUserID :one
SELECT COUNT(*) FROM api_keys WHERE user_id = $1
`

func (q *Queries) APIKeyCountByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, aPIKeyCountByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const aPIKeyCreate = `-- name: APIKeyCreate :one

INSERT INTO api_keys (user_id, name, key_prefix, key_hash, kind, permissions, expires_at, project_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, key_prefix, kind, permissions, project_id, last_used_at, expires_at, created_at
`

type APIKeyCreateParams struct {
	UserID      string                  `db:"user_id" json:"user_id"`
	Name        string                  `db:"name" json:"name"`
	KeyPrefix   string                  `db:"key_prefix" json:"key_prefix"`
	KeyHash     string                  `db:"key_hash" json:"key_hash"`
	Kind        string                  `db:"kind" json:"kind"`
	Permissions model.APIKeyPermissions `db:"permissions" json:"permissions"`
	ExpiresAt   *time.Time              `db:"expires_at" json:"expires_at"`
	ProjectID   *string                 `db:"project_id" json:"project_id"`
}

type APIKeyCreateRow struct {
	ID          string                  `db:"id" json:"id"`
	UserID      string                  `db:"user_id" json:"user_id"`
	Name        string                  `db:"name" json:"name"`
	KeyPrefix   string                  `db:"key_prefix" json:"key_prefix"`
	Kind        string                  `db:"kind" json:"kind"`
	Permissions model.APIKeyPermissions `db:"permissions" json:"permissions"`
	ProjectID   *string                 `db:"project_id" json:"project_id"`
	LastUsedAt  *time.Time              `db:"last_used_at" json:"last_used_at"`
	ExpiresAt   *time.Time              `db:"expires_at" json:"expires_at"`
	CreatedAt   time.Time               `db:"created_at" json:"created_at"`
}

// ============================================================================
// APIKey static queries (sqlc-generated)
//
// FindByKeyHash (JOIN that splits into two separate model structs) stays as
// hand-written pgx in internal/repository/api_key.go.
// ============================================================================
func (q *Queries) APIKeyCreate(ctx context.Context, arg APIKeyCreateParams) (APIKeyCreateRow, error) {
	row := q.db.QueryRow(ctx, aPIKeyCreate,
		arg.UserID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Kind,
		arg.Permissions,
		arg.ExpiresAt,
		arg.ProjectID,
	)
	var i APIKeyCreateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.Kind,
		&i.Permissions,
		&i.ProjectID,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const aPIKeyDelete = `-- name: APIKeyDelete :execrows
DELETE FROM api_keys WHERE id = $1 AND user_id = $2
`

type APIKeyDeleteParams struct {
	ID     string `db:"id" json:"id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) APIKeyDelete(ctx context.Context, arg APIKeyDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, aPIKeyDelete, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const aPIKeyFindByUserID = `-- name: APIKeyFindByUserID :many
SELECT id, user_id, name, key_prefix, kind, permissions, project_id, last_used_at, expires_at, created_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type APIKeyFindByUserIDRow struct {
	ID          string                  `db:"id" json:"id"`
	UserID      string                  `db:"user_id" json:"user_id"`
	Name        string                  `db:"name" json:"name"`
	KeyPrefix   string                  `db:"key_prefix" json:"key_prefix"`
	Kind        string                  `db:"kind" json:"kind"`
	Permissions model.APIKeyPermissions `db:"permissions" json:"permissions"`
	ProjectID   *string                 `db:"project_id" json:"project_id"`
	LastUsedAt  *time.Time              `db:"last_used_at" json:"last_used_at"`
	ExpiresAt   *time.Time              `db:"expires_at" json:"expires_at"`
	CreatedAt   time.Time               `db:"created_at" json:"created_at"`
}

func (q *Queries) APIKeyFindByUserID(ctx context.Context, userID string) ([]APIKeyFindByUserIDRow, error) {
	rows, err := q.db.Query(ctx, aPIKeyFindByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []APIKeyFindByUserIDRow{}
	for rows.Next() {
		var i APIKeyFindByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.Kind,
			&i.Permissions,
			&i.ProjectID,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIKeyUpdateLastUsed = `-- name: APIKeyUpdateLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) APIKeyUpdateLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, aPIKeyUpdateLastUsed, id)
	return err
}
