// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment.sql

package dbgen

import (
	"context"
)

const attachmentCreate = `-- name: AttachmentCreate :one

INSERT INTO node_attachments
    (node_id, project_id, filename, mime_type, size_bytes,
     storage_key, sha256, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, node_id, project_id, filename, mime_type, size_bytes,
          storage_key, sha256, uploaded_by, created_at
`

type AttachmentCreateParams struct {
	NodeID     string `db:"node_id" json:"node_id"`
	ProjectID  string `db:"project_id" json:"project_id"`
	Filename   string `db:"filename" json:"filename"`
	MimeType   string `db:"mime_type" json:"mime_type"`
	SizeBytes  int64  `db:"size_bytes" json:"size_bytes"`
	StorageKey string `db:"storage_key" json:"storage_key"`
	Sha256     string `db:"sha256" json:"sha256"`
	UploadedBy string `db:"uploaded_by" json:"uploaded_by"`
}

// ============================================================================
// Node attachment queries (v0.6.0 B-2). Filesystem-backed for now; storage_key
// is a relative path inside THASK_ATTACHMENT_DIR (see cmd/server/main.go and
// docker-compose.yml). MinIO/S3 swap-in later reuses the same rows.
// ============================================================================
func (q *Queries) AttachmentCreate(ctx context.Context, arg AttachmentCreateParams) (NodeAttachment, error) {
	row := q.db.QueryRow(ctx, attachmentCreate,
		arg.NodeID,
		arg.ProjectID,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.Sha256,
		arg.UploadedBy,
	)
	var i NodeAttachment
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ProjectID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const attachmentDelete = `-- name: AttachmentDelete :execrows
DELETE FROM node_attachments WHERE id = $1 AND project_id = $2
`

type AttachmentDeleteParams struct {
	ID        string `db:"id" json:"id"`
	ProjectID string `db:"project_id" json:"project_id"`
}

func (q *Queries) AttachmentDelete(ctx context.Context, arg AttachmentDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachmentDelete, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const attachmentFindByID = `-- name: AttachmentFindByID :one
SELECT id, node_id, project_id, filename, mime_type, size_bytes,
       storage_key, sha256, uploaded_by, created_at
FROM node_attachments
WHERE id = $1
`

func (q *Queries) AttachmentFindByID(ctx context.Context, id string) (NodeAttachment, error) {
	row := q.db.QueryRow(ctx, attachmentFindByID, id)
	var i NodeAttachment
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ProjectID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Sha256,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const attachmentFindByNode = `-- name: AttachmentFindByNode :many
SELECT id, node_id, project_id, filename, mime_type, size_bytes,
       storage_key, sha256, uploaded_by, created_at
FROM node_attachments
WHERE node_id = $1
ORDER BY created_at DESC
`

func (q *Queries) AttachmentFindByNode(ctx context.Context, nodeID string) ([]NodeAttachment, error) {
	rows, err := q.db.Query(ctx, attachmentFindByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeAttachment{}
	for rows.Next() {
		var i NodeAttachment
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ProjectID,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.Sha256,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
