// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"
	"encoding/json"
)

const auditLogInsert = `-- name: AuditLogInsert :exec

INSERT INTO audit_log (
    project_id, entity_type, entity_id, action, field_name,
    old_value, new_value, mutation_kind, user_id, api_key_id,
    actor_kind, client_type, client_version, agent_model, agent_session_id,
    trigger, batch_id, code_commit, source_path, confidence, metadata
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21
)
`

type AuditLogInsertParams struct {
	ProjectID      string          `db:"project_id" json:"project_id"`
	EntityType     string          `db:"entity_type" json:"entity_type"`
	EntityID       *string         `db:"entity_id" json:"entity_id"`
	Action         string          `db:"action" json:"action"`
	FieldName      *string         `db:"field_name" json:"field_name"`
	OldValue       *string         `db:"old_value" json:"old_value"`
	NewValue       *string         `db:"new_value" json:"new_value"`
	MutationKind   string          `db:"mutation_kind" json:"mutation_kind"`
	UserID         *string         `db:"user_id" json:"user_id"`
	ApiKeyID       *string         `db:"api_key_id" json:"api_key_id"`
	ActorKind      string          `db:"actor_kind" json:"actor_kind"`
	ClientType     *string         `db:"client_type" json:"client_type"`
	ClientVersion  *string         `db:"client_version" json:"client_version"`
	AgentModel     *string         `db:"agent_model" json:"agent_model"`
	AgentSessionID *string         `db:"agent_session_id" json:"agent_session_id"`
	Trigger        *string         `db:"trigger" json:"trigger"`
	BatchID        *string         `db:"batch_id" json:"batch_id"`
	CodeCommit     *string         `db:"code_commit" json:"code_commit"`
	SourcePath     *string         `db:"source_path" json:"source_path"`
	Confidence     *string         `db:"confidence" json:"confidence"`
	Metadata       json.RawMessage `db:"metadata" json:"metadata"`
}

// ============================================================================
// AuditLog static queries (sqlc-generated)
// ============================================================================
func (q *Queries) AuditLogInsert(ctx context.Context, arg AuditLogInsertParams) error {
	_, err := q.db.Exec(ctx, auditLogInsert,
		arg.ProjectID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
		arg.MutationKind,
		arg.UserID,
		arg.ApiKeyID,
		arg.ActorKind,
		arg.ClientType,
		arg.ClientVersion,
		arg.AgentModel,
		arg.AgentSessionID,
		arg.Trigger,
		arg.BatchID,
		arg.CodeCommit,
		arg.SourcePath,
		arg.Confidence,
		arg.Metadata,
	)
	return err
}

const auditLogListByEntity = `-- name: AuditLogListByEntity :many
SELECT id, project_id, entity_type, entity_id, action, field_name,
       old_value, new_value, mutation_kind, user_id, api_key_id,
       actor_kind, client_type, client_version, agent_model, agent_session_id,
       trigger, batch_id, code_commit, source_path, confidence, metadata, created_at
FROM audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type AuditLogListByEntityParams struct {
	EntityType string  `db:"entity_type" json:"entity_type"`
	EntityID   *string `db:"entity_id" json:"entity_id"`
	Limit      int32   `db:"limit" json:"limit"`
}

func (q *Queries) AuditLogListByEntity(ctx context.Context, arg AuditLogListByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, auditLogListByEntity, arg.EntityType, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.MutationKind,
			&i.UserID,
			&i.ApiKeyID,
			&i.ActorKind,
			&i.ClientType,
			&i.ClientVersion,
			&i.AgentModel,
			&i.AgentSessionID,
			&i.Trigger,
			&i.BatchID,
			&i.CodeCommit,
			&i.SourcePath,
			&i.Confidence,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
