// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package dbgen

import (
	"context"
)

const commentCreate = `-- name: CommentCreate :one

INSERT INTO node_comments (node_id, project_id, author_id, parent_id, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, node_id, project_id, author_id, parent_id, body,
          resolved_at, resolved_by, created_at, updated_at
`

type CommentCreateParams struct {
	NodeID    string  `db:"node_id" json:"node_id"`
	ProjectID string  `db:"project_id" json:"project_id"`
	AuthorID  string  `db:"author_id" json:"author_id"`
	ParentID  *string `db:"parent_id" json:"parent_id"`
	Body      string  `db:"body" json:"body"`
}

// ============================================================================
// Node comment queries (v0.6.0 B-1). Threaded discussion attached to any node.
// parent_id is self-referential for one-level threading; deeper nesting is
// out of scope for v0.6.0.
// ============================================================================
func (q *Queries) CommentCreate(ctx context.Context, arg CommentCreateParams) (NodeComment, error) {
	row := q.db.QueryRow(ctx, commentCreate,
		arg.NodeID,
		arg.ProjectID,
		arg.AuthorID,
		arg.ParentID,
		arg.Body,
	)
	var i NodeComment
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ProjectID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const commentDelete = `-- name: CommentDelete :execrows
DELETE FROM node_comments WHERE id = $1 AND project_id = $2 AND author_id = $3
`

type CommentDeleteParams struct {
	ID        string `db:"id" json:"id"`
	ProjectID string `db:"project_id" json:"project_id"`
	AuthorID  string `db:"author_id" json:"author_id"`
}

func (q *Queries) CommentDelete(ctx context.Context, arg CommentDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, commentDelete, arg.ID, arg.ProjectID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const commentFindByNode = `-- name: CommentFindByNode :many
SELECT id, node_id, project_id, author_id, parent_id, body,
       resolved_at, resolved_by, created_at, updated_at
FROM node_comments
WHERE node_id = $1
ORDER BY created_at ASC
`

func (q *Queries) CommentFindByNode(ctx context.Context, nodeID string) ([]NodeComment, error) {
	rows, err := q.db.Query(ctx, commentFindByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeComment{}
	for rows.Next() {
		var i NodeComment
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ProjectID,
			&i.AuthorID,
			&i.ParentID,
			&i.Body,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const commentFindByProjectUnresolved = `-- name: CommentFindByProjectUnresolved :many
SELECT id, node_id, project_id, author_id, parent_id, body,
       resolved_at, resolved_by, created_at, updated_at
FROM node_comments
WHERE project_id = $1 AND resolved_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type CommentFindByProjectUnresolvedParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Limit     int32  `db:"limit" json:"limit"`
}

func (q *Queries) CommentFindByProjectUnresolved(ctx context.Context, arg CommentFindByProjectUnresolvedParams) ([]NodeComment, error) {
	rows, err := q.db.Query(ctx, commentFindByProjectUnresolved, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeComment{}
	for rows.Next() {
		var i NodeComment
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ProjectID,
			&i.AuthorID,
			&i.ParentID,
			&i.Body,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const commentResolve = `-- name: CommentResolve :one
UPDATE node_comments
SET resolved_at = now(), resolved_by = $1, updated_at = now()
WHERE id = $2 AND project_id = $3 AND resolved_at IS NULL
RETURNING id, node_id, project_id, author_id, parent_id, body,
          resolved_at, resolved_by, created_at, updated_at
`

type CommentResolveParams struct {
	ResolvedBy *string `db:"resolved_by" json:"resolved_by"`
	ID         string  `db:"id" json:"id"`
	ProjectID  string  `db:"project_id" json:"project_id"`
}

func (q *Queries) CommentResolve(ctx context.Context, arg CommentResolveParams) (NodeComment, error) {
	row := q.db.QueryRow(ctx, commentResolve, arg.ResolvedBy, arg.ID, arg.ProjectID)
	var i NodeComment
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ProjectID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const commentUpdateBody = `-- name: CommentUpdateBody :one
UPDATE node_comments
SET body = $1, updated_at = now()
WHERE id = $2 AND project_id = $3 AND author_id = $4
RETURNING id, node_id, project_id, author_id, parent_id, body,
          resolved_at, resolved_by, created_at, updated_at
`

type CommentUpdateBodyParams struct {
	Body      string `db:"body" json:"body"`
	ID        string `db:"id" json:"id"`
	ProjectID string `db:"project_id" json:"project_id"`
	AuthorID  string `db:"author_id" json:"author_id"`
}

func (q *Queries) CommentUpdateBody(ctx context.Context, arg CommentUpdateBodyParams) (NodeComment, error) {
	row := q.db.QueryRow(ctx, commentUpdateBody,
		arg.Body,
		arg.ID,
		arg.ProjectID,
		arg.AuthorID,
	)
	var i NodeComment
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ProjectID,
		&i.AuthorID,
		&i.ParentID,
		&i.Body,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
