// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edge.sql

package dbgen

import (
	"context"
	"time"
)

const edgeCreate = `-- name: EdgeCreate :one

INSERT INTO edges (project_id, source_id, target_id, edge_type, label)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, source_id, target_id, edge_type, label, source_port, target_port, waypoints, created_at
`

type EdgeCreateParams struct {
	ProjectID string  `db:"project_id" json:"project_id"`
	SourceID  string  `db:"source_id" json:"source_id"`
	TargetID  string  `db:"target_id" json:"target_id"`
	EdgeType  string  `db:"edge_type" json:"edge_type"`
	Label     *string `db:"label" json:"label"`
}

type EdgeCreateRow struct {
	ID         string    `db:"id" json:"id"`
	ProjectID  string    `db:"project_id" json:"project_id"`
	SourceID   string    `db:"source_id" json:"source_id"`
	TargetID   string    `db:"target_id" json:"target_id"`
	EdgeType   string    `db:"edge_type" json:"edge_type"`
	Label      *string   `db:"label" json:"label"`
	SourcePort string    `db:"source_port" json:"source_port"`
	TargetPort string    `db:"target_port" json:"target_port"`
	Waypoints  []byte    `db:"waypoints" json:"waypoints"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

// ============================================================================
// Edge static queries (sqlc-generated)
//
// Dynamic queries (FindByProjectIDPaginated with cursor, BatchUpdateWaypoints
// loop) stay as hand-written pgx in internal/repository/edge.go.
// ============================================================================
func (q *Queries) EdgeCreate(ctx context.Context, arg EdgeCreateParams) (EdgeCreateRow, error) {
	row := q.db.QueryRow(ctx, edgeCreate,
		arg.ProjectID,
		arg.SourceID,
		arg.TargetID,
		arg.EdgeType,
		arg.Label,
	)
	var i EdgeCreateRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.TargetID,
		&i.EdgeType,
		&i.Label,
		&i.SourcePort,
		&i.TargetPort,
		&i.Waypoints,
		&i.CreatedAt,
	)
	return i, err
}

const edgeCreateWithRouting = `-- name: EdgeCreateWithRouting :one
INSERT INTO edges (project_id, source_id, target_id, edge_type, label, source_port, target_port, waypoints)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, source_id, target_id, edge_type, label, source_port, target_port, waypoints, created_at
`

type EdgeCreateWithRoutingParams struct {
	ProjectID  string  `db:"project_id" json:"project_id"`
	SourceID   string  `db:"source_id" json:"source_id"`
	TargetID   string  `db:"target_id" json:"target_id"`
	EdgeType   string  `db:"edge_type" json:"edge_type"`
	Label      *string `db:"label" json:"label"`
	SourcePort string  `db:"source_port" json:"source_port"`
	TargetPort string  `db:"target_port" json:"target_port"`
	Waypoints  []byte  `db:"waypoints" json:"waypoints"`
}

type EdgeCreateWithRoutingRow struct {
	ID         string    `db:"id" json:"id"`
	ProjectID  string    `db:"project_id" json:"project_id"`
	SourceID   string    `db:"source_id" json:"source_id"`
	TargetID   string    `db:"target_id" json:"target_id"`
	EdgeType   string    `db:"edge_type" json:"edge_type"`
	Label      *string   `db:"label" json:"label"`
	SourcePort string    `db:"source_port" json:"source_port"`
	TargetPort string    `db:"target_port" json:"target_port"`
	Waypoints  []byte    `db:"waypoints" json:"waypoints"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) EdgeCreateWithRouting(ctx context.Context, arg EdgeCreateWithRoutingParams) (EdgeCreateWithRoutingRow, error) {
	row := q.db.QueryRow(ctx, edgeCreateWithRouting,
		arg.ProjectID,
		arg.SourceID,
		arg.TargetID,
		arg.EdgeType,
		arg.Label,
		arg.SourcePort,
		arg.TargetPort,
		arg.Waypoints,
	)
	var i EdgeCreateWithRoutingRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.TargetID,
		&i.EdgeType,
		&i.Label,
		&i.SourcePort,
		&i.TargetPort,
		&i.Waypoints,
		&i.CreatedAt,
	)
	return i, err
}

const edgeDelete = `-- name: EdgeDelete :exec
DELETE FROM edges WHERE id = $1
`

func (q *Queries) EdgeDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, edgeDelete, id)
	return err
}

const edgeDeleteScoped = `-- name: EdgeDeleteScoped :execrows
DELETE FROM edges WHERE id = $1 AND project_id = $2
`

type EdgeDeleteScopedParams struct {
	ID        string `db:"id" json:"id"`
	ProjectID string `db:"project_id" json:"project_id"`
}

func (q *Queries) EdgeDeleteScoped(ctx context.Context, arg EdgeDeleteScopedParams) (int64, error) {
	result, err := q.db.Exec(ctx, edgeDeleteScoped, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const edgeFindByProjectID = `-- name: EdgeFindByProjectID :many
SELECT id, project_id, source_id, target_id, edge_type, label, source_port, target_port, waypoints, created_at
FROM edges
WHERE project_id = $1
`

type EdgeFindByProjectIDRow struct {
	ID         string    `db:"id" json:"id"`
	ProjectID  string    `db:"project_id" json:"project_id"`
	SourceID   string    `db:"source_id" json:"source_id"`
	TargetID   string    `db:"target_id" json:"target_id"`
	EdgeType   string    `db:"edge_type" json:"edge_type"`
	Label      *string   `db:"label" json:"label"`
	SourcePort string    `db:"source_port" json:"source_port"`
	TargetPort string    `db:"target_port" json:"target_port"`
	Waypoints  []byte    `db:"waypoints" json:"waypoints"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) EdgeFindByProjectID(ctx context.Context, projectID string) ([]EdgeFindByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, edgeFindByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdgeFindByProjectIDRow{}
	for rows.Next() {
		var i EdgeFindByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.TargetID,
			&i.EdgeType,
			&i.Label,
			&i.SourcePort,
			&i.TargetPort,
			&i.Waypoints,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const edgeFindConnected = `-- name: EdgeFindConnected :many
SELECT id, project_id, source_id, target_id, edge_type, label, source_port, target_port, waypoints, created_at
FROM edges
WHERE source_id = $1 OR target_id = $1
`

type EdgeFindConnectedRow struct {
	ID         string    `db:"id" json:"id"`
	ProjectID  string    `db:"project_id" json:"project_id"`
	SourceID   string    `db:"source_id" json:"source_id"`
	TargetID   string    `db:"target_id" json:"target_id"`
	EdgeType   string    `db:"edge_type" json:"edge_type"`
	Label      *string   `db:"label" json:"label"`
	SourcePort string    `db:"source_port" json:"source_port"`
	TargetPort string    `db:"target_port" json:"target_port"`
	Waypoints  []byte    `db:"waypoints" json:"waypoints"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) EdgeFindConnected(ctx context.Context, sourceID string) ([]EdgeFindConnectedRow, error) {
	rows, err := q.db.Query(ctx, edgeFindConnected, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdgeFindConnectedRow{}
	for rows.Next() {
		var i EdgeFindConnectedRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.TargetID,
			&i.EdgeType,
			&i.Label,
			&i.SourcePort,
			&i.TargetPort,
			&i.Waypoints,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const edgeListNodeIDsInProject = `-- name: EdgeListNodeIDsInProject :many
SELECT id FROM nodes
WHERE project_id = $1
  AND id = ANY($2::uuid[])
`

type EdgeListNodeIDsInProjectParams struct {
	ProjectID string   `db:"project_id" json:"project_id"`
	NodeIds   []string `db:"node_ids" json:"node_ids"`
}

// Returns the subset of supplied IDs that actually live in the project.
// Used by edge BatchCreate to filter cross-project endpoints into the
// 207-style skipped[] response instead of corrupting the graph.
func (q *Queries) EdgeListNodeIDsInProject(ctx context.Context, arg EdgeListNodeIDsInProjectParams) ([]string, error) {
	rows, err := q.db.Query(ctx, edgeListNodeIDsInProject, arg.ProjectID, arg.NodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const edgeResetWaypoints = `-- name: EdgeResetWaypoints :exec
UPDATE edges SET waypoints = '[]', source_port = 'auto', target_port = 'auto'
WHERE project_id = $1
`

func (q *Queries) EdgeResetWaypoints(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, edgeResetWaypoints, projectID)
	return err
}

const edgeUpdate = `-- name: EdgeUpdate :one
UPDATE edges SET
  edge_type = COALESCE($1, edge_type),
  label = COALESCE($2, label)
WHERE id = $3
RETURNING id, project_id, source_id, target_id, edge_type, label, source_port, target_port, waypoints, created_at
`

type EdgeUpdateParams struct {
	EdgeType string  `db:"edge_type" json:"edge_type"`
	Label    *string `db:"label" json:"label"`
	ID       string  `db:"id" json:"id"`
}

type EdgeUpdateRow struct {
	ID         string    `db:"id" json:"id"`
	ProjectID  string    `db:"project_id" json:"project_id"`
	SourceID   string    `db:"source_id" json:"source_id"`
	TargetID   string    `db:"target_id" json:"target_id"`
	EdgeType   string    `db:"edge_type" json:"edge_type"`
	Label      *string   `db:"label" json:"label"`
	SourcePort string    `db:"source_port" json:"source_port"`
	TargetPort string    `db:"target_port" json:"target_port"`
	Waypoints  []byte    `db:"waypoints" json:"waypoints"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) EdgeUpdate(ctx context.Context, arg EdgeUpdateParams) (EdgeUpdateRow, error) {
	row := q.db.QueryRow(ctx, edgeUpdate, arg.EdgeType, arg.Label, arg.ID)
	var i EdgeUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.TargetID,
		&i.EdgeType,
		&i.Label,
		&i.SourcePort,
		&i.TargetPort,
		&i.Waypoints,
		&i.CreatedAt,
	)
	return i, err
}

const edgeUpdateRouting = `-- name: EdgeUpdateRouting :one
UPDATE edges SET
  source_port = COALESCE($1, source_port),
  target_port = COALESCE($2, target_port),
  waypoints = COALESCE($3, waypoints)
WHERE id = $4
RETURNING id, project_id, source_id, target_id, edge_type, label, source_port, target_port, waypoints, created_at
`

type EdgeUpdateRoutingParams struct {
	SourcePort string `db:"source_port" json:"source_port"`
	TargetPort string `db:"target_port" json:"target_port"`
	Waypoints  []byte `db:"waypoints" json:"waypoints"`
	ID         string `db:"id" json:"id"`
}

type EdgeUpdateRoutingRow struct {
	ID         string    `db:"id" json:"id"`
	ProjectID  string    `db:"project_id" json:"project_id"`
	SourceID   string    `db:"source_id" json:"source_id"`
	TargetID   string    `db:"target_id" json:"target_id"`
	EdgeType   string    `db:"edge_type" json:"edge_type"`
	Label      *string   `db:"label" json:"label"`
	SourcePort string    `db:"source_port" json:"source_port"`
	TargetPort string    `db:"target_port" json:"target_port"`
	Waypoints  []byte    `db:"waypoints" json:"waypoints"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) EdgeUpdateRouting(ctx context.Context, arg EdgeUpdateRoutingParams) (EdgeUpdateRoutingRow, error) {
	row := q.db.QueryRow(ctx, edgeUpdateRouting,
		arg.SourcePort,
		arg.TargetPort,
		arg.Waypoints,
		arg.ID,
	)
	var i EdgeUpdateRoutingRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.TargetID,
		&i.EdgeType,
		&i.Label,
		&i.SourcePort,
		&i.TargetPort,
		&i.Waypoints,
		&i.CreatedAt,
	)
	return i, err
}

const edgeVerifyNodesInProject = `-- name: EdgeVerifyNodesInProject :one
SELECT COUNT(*) FROM nodes
WHERE project_id = $1
  AND id = ANY($2::uuid[])
`

type EdgeVerifyNodesInProjectParams struct {
	ProjectID string   `db:"project_id" json:"project_id"`
	NodeIds   []string `db:"node_ids" json:"node_ids"`
}

// Returns the count of the given node IDs that actually live in the specified
// project. Used by edge create paths to reject cross-project source/target —
// without this check, an authenticated caller can pass IDs from another
// project they have access to and end up with corrupt edge.project_id rows.
func (q *Queries) EdgeVerifyNodesInProject(ctx context.Context, arg EdgeVerifyNodesInProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, edgeVerifyNodesInProject, arg.ProjectID, arg.NodeIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const edgeVerifyProject = `-- name: EdgeVerifyProject :one
SELECT EXISTS(SELECT 1 FROM edges WHERE id = $1 AND project_id = $2)
`

type EdgeVerifyProjectParams struct {
	ID        string `db:"id" json:"id"`
	ProjectID string `db:"project_id" json:"project_id"`
}

func (q *Queries) EdgeVerifyProject(ctx context.Context, arg EdgeVerifyProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, edgeVerifyProject, arg.ID, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
