// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package dbgen

import (
	"context"
	"time"
)

const historyCreate = `-- name: HistoryCreate :exec

INSERT INTO node_history (node_id, project_id, user_id, action, field_name, old_value, new_value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type HistoryCreateParams struct {
	NodeID    string      `db:"node_id" json:"node_id"`
	ProjectID string      `db:"project_id" json:"project_id"`
	UserID    string      `db:"user_id" json:"user_id"`
	Action    interface{} `db:"action" json:"action"`
	FieldName *string     `db:"field_name" json:"field_name"`
	OldValue  *string     `db:"old_value" json:"old_value"`
	NewValue  *string     `db:"new_value" json:"new_value"`
}

// ============================================================================
// NodeHistory static queries (sqlc-generated)
//
// BatchCreateStatusChanges stays as hand-written pgx (dynamic multi-row INSERT
// with fmt.Sprintf).
// ============================================================================
func (q *Queries) HistoryCreate(ctx context.Context, arg HistoryCreateParams) error {
	_, err := q.db.Exec(ctx, historyCreate,
		arg.NodeID,
		arg.ProjectID,
		arg.UserID,
		arg.Action,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const historyFindByNodeID = `-- name: HistoryFindByNodeID :many
SELECT nh.id, nh.action, nh.field_name, nh.old_value, nh.new_value, nh.created_at, u.display_name
FROM node_history nh
INNER JOIN users u ON nh.user_id = u.id
WHERE nh.node_id = $1
ORDER BY nh.created_at DESC
LIMIT $2
`

type HistoryFindByNodeIDParams struct {
	NodeID string `db:"node_id" json:"node_id"`
	Limit  int32  `db:"limit" json:"limit"`
}

type HistoryFindByNodeIDRow struct {
	ID          string      `db:"id" json:"id"`
	Action      interface{} `db:"action" json:"action"`
	FieldName   *string     `db:"field_name" json:"field_name"`
	OldValue    *string     `db:"old_value" json:"old_value"`
	NewValue    *string     `db:"new_value" json:"new_value"`
	CreatedAt   time.Time   `db:"created_at" json:"created_at"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

func (q *Queries) HistoryFindByNodeID(ctx context.Context, arg HistoryFindByNodeIDParams) ([]HistoryFindByNodeIDRow, error) {
	rows, err := q.db.Query(ctx, historyFindByNodeID, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoryFindByNodeIDRow{}
	for rows.Next() {
		var i HistoryFindByNodeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyFindByProjectID = `-- name: HistoryFindByProjectID :many
SELECT nh.id, nh.action, nh.field_name, nh.old_value, nh.new_value, nh.created_at, u.display_name
FROM node_history nh
INNER JOIN users u ON nh.user_id = u.id
WHERE nh.project_id = $1
ORDER BY nh.created_at DESC
LIMIT $2
`

type HistoryFindByProjectIDParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Limit     int32  `db:"limit" json:"limit"`
}

type HistoryFindByProjectIDRow struct {
	ID          string      `db:"id" json:"id"`
	Action      interface{} `db:"action" json:"action"`
	FieldName   *string     `db:"field_name" json:"field_name"`
	OldValue    *string     `db:"old_value" json:"old_value"`
	NewValue    *string     `db:"new_value" json:"new_value"`
	CreatedAt   time.Time   `db:"created_at" json:"created_at"`
	DisplayName string      `db:"display_name" json:"display_name"`
}

func (q *Queries) HistoryFindByProjectID(ctx context.Context, arg HistoryFindByProjectIDParams) ([]HistoryFindByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, historyFindByProjectID, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoryFindByProjectIDRow{}
	for rows.Next() {
		var i HistoryFindByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
