// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package dbgen

import (
	"context"
	"time"
)

const historyCreate = `-- name: HistoryCreate :exec

INSERT INTO node_history (node_id, project_id, user_id, action, field_name, old_value, new_value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type HistoryCreateParams struct {
	NodeID    string  `db:"node_id" json:"node_id"`
	ProjectID string  `db:"project_id" json:"project_id"`
	UserID    string  `db:"user_id" json:"user_id"`
	Action    string  `db:"action" json:"action"`
	FieldName *string `db:"field_name" json:"field_name"`
	OldValue  *string `db:"old_value" json:"old_value"`
	NewValue  *string `db:"new_value" json:"new_value"`
}

// ============================================================================
// NodeHistory static queries (sqlc-generated)
//
// BatchCreateStatusChanges stays as hand-written pgx (dynamic multi-row INSERT
// with fmt.Sprintf).
// ============================================================================
func (q *Queries) HistoryCreate(ctx context.Context, arg HistoryCreateParams) error {
	_, err := q.db.Exec(ctx, historyCreate,
		arg.NodeID,
		arg.ProjectID,
		arg.UserID,
		arg.Action,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const historyFindByNodeID = `-- name: HistoryFindByNodeID :many
SELECT a.id, a.action, a.field_name, a.old_value, a.new_value, a.created_at,
       COALESCE(u.display_name, '')::text AS display_name
FROM audit_log a
LEFT JOIN users u ON u.id = a.user_id
WHERE a.entity_id = $1 AND a.entity_type = 'node'
ORDER BY a.created_at DESC
LIMIT $2
`

type HistoryFindByNodeIDParams struct {
	EntityID *string `db:"entity_id" json:"entity_id"`
	Limit    int32   `db:"limit" json:"limit"`
}

type HistoryFindByNodeIDRow struct {
	ID          string    `db:"id" json:"id"`
	Action      string    `db:"action" json:"action"`
	FieldName   *string   `db:"field_name" json:"field_name"`
	OldValue    *string   `db:"old_value" json:"old_value"`
	NewValue    *string   `db:"new_value" json:"new_value"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	DisplayName string    `db:"display_name" json:"display_name"`
}

func (q *Queries) HistoryFindByNodeID(ctx context.Context, arg HistoryFindByNodeIDParams) ([]HistoryFindByNodeIDRow, error) {
	rows, err := q.db.Query(ctx, historyFindByNodeID, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoryFindByNodeIDRow{}
	for rows.Next() {
		var i HistoryFindByNodeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyFindByProjectID = `-- name: HistoryFindByProjectID :many

SELECT a.id, a.action, a.field_name, a.old_value, a.new_value, a.created_at,
       COALESCE(u.display_name, '')::text AS display_name
FROM audit_log a
LEFT JOIN users u ON u.id = a.user_id
WHERE a.project_id = $1 AND a.entity_type = 'node'
ORDER BY a.created_at DESC
LIMIT $2
`

type HistoryFindByProjectIDParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Limit     int32  `db:"limit" json:"limit"`
}

type HistoryFindByProjectIDRow struct {
	ID          string    `db:"id" json:"id"`
	Action      string    `db:"action" json:"action"`
	FieldName   *string   `db:"field_name" json:"field_name"`
	OldValue    *string   `db:"old_value" json:"old_value"`
	NewValue    *string   `db:"new_value" json:"new_value"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	DisplayName string    `db:"display_name" json:"display_name"`
}

// v0.6.0: reads now come from audit_log (node_history is deprecated and its
// writes were disabled in v0.6.0). Migration 010 backfilled every prior
// node_history row into audit_log, so callers see one continuous timeline
// covering both pre- and post-v0.6.0 activity without stitching two tables.
// Only node entity events are surfaced here — edges/projects/graph events
// live in their own audit views.
func (q *Queries) HistoryFindByProjectID(ctx context.Context, arg HistoryFindByProjectIDParams) ([]HistoryFindByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, historyFindByProjectID, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoryFindByProjectIDRow{}
	for rows.Next() {
		var i HistoryFindByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
