// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package dbgen

import (
	"context"
)

const idempotencyCleanup = `-- name: IdempotencyCleanup :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) IdempotencyCleanup(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, idempotencyCleanup)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const idempotencyFind = `-- name: IdempotencyFind :one

SELECT key, api_key_id, method, path, status_code, response, created_at, expires_at
FROM idempotency_keys
WHERE key = $1 AND api_key_id = $2 AND expires_at > now()
`

type IdempotencyFindParams struct {
	Key      string `db:"key" json:"key"`
	ApiKeyID string `db:"api_key_id" json:"api_key_id"`
}

// ============================================================================
// Idempotency static queries (sqlc-generated)
// ============================================================================
func (q *Queries) IdempotencyFind(ctx context.Context, arg IdempotencyFindParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, idempotencyFind, arg.Key, arg.ApiKeyID)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ApiKeyID,
		&i.Method,
		&i.Path,
		&i.StatusCode,
		&i.Response,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const idempotencyTryClaim = `-- name: IdempotencyTryClaim :one
INSERT INTO idempotency_keys (key, api_key_id, method, path, status_code, response)
VALUES ($1, $2, $3, $4, 0, '{}'::jsonb)
ON CONFLICT (key, api_key_id) DO UPDATE SET key = idempotency_keys.key
RETURNING key, api_key_id, method, path, status_code, response, created_at, expires_at
`

type IdempotencyTryClaimParams struct {
	Key      string `db:"key" json:"key"`
	ApiKeyID string `db:"api_key_id" json:"api_key_id"`
	Method   string `db:"method" json:"method"`
	Path     string `db:"path" json:"path"`
}

func (q *Queries) IdempotencyTryClaim(ctx context.Context, arg IdempotencyTryClaimParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, idempotencyTryClaim,
		arg.Key,
		arg.ApiKeyID,
		arg.Method,
		arg.Path,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ApiKeyID,
		&i.Method,
		&i.Path,
		&i.StatusCode,
		&i.Response,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const idempotencyUpdateResponse = `-- name: IdempotencyUpdateResponse :exec
UPDATE idempotency_keys SET status_code = $3, response = $4 WHERE key = $1 AND api_key_id = $2
`

type IdempotencyUpdateResponseParams struct {
	Key        string `db:"key" json:"key"`
	ApiKeyID   string `db:"api_key_id" json:"api_key_id"`
	StatusCode int32  `db:"status_code" json:"status_code"`
	Response   []byte `db:"response" json:"response"`
}

func (q *Queries) IdempotencyUpdateResponse(ctx context.Context, arg IdempotencyUpdateResponseParams) error {
	_, err := q.db.Exec(ctx, idempotencyUpdateResponse,
		arg.Key,
		arg.ApiKeyID,
		arg.StatusCode,
		arg.Response,
	)
	return err
}
