// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"encoding/json"
	"time"

	model "github.com/thask/backend/internal/model"
)

type ApiKey struct {
	ID          string                  `db:"id" json:"id"`
	UserID      string                  `db:"user_id" json:"user_id"`
	Name        string                  `db:"name" json:"name"`
	KeyPrefix   string                  `db:"key_prefix" json:"key_prefix"`
	KeyHash     string                  `db:"key_hash" json:"key_hash"`
	LastUsedAt  *time.Time              `db:"last_used_at" json:"last_used_at"`
	ExpiresAt   *time.Time              `db:"expires_at" json:"expires_at"`
	CreatedAt   time.Time               `db:"created_at" json:"created_at"`
	Kind        string                  `db:"kind" json:"kind"`
	Permissions model.APIKeyPermissions `db:"permissions" json:"permissions"`
}

type AuditLog struct {
	ID             string          `db:"id" json:"id"`
	ProjectID      string          `db:"project_id" json:"project_id"`
	EntityType     string          `db:"entity_type" json:"entity_type"`
	EntityID       *string         `db:"entity_id" json:"entity_id"`
	Action         string          `db:"action" json:"action"`
	FieldName      *string         `db:"field_name" json:"field_name"`
	OldValue       *string         `db:"old_value" json:"old_value"`
	NewValue       *string         `db:"new_value" json:"new_value"`
	MutationKind   string          `db:"mutation_kind" json:"mutation_kind"`
	UserID         *string         `db:"user_id" json:"user_id"`
	ApiKeyID       *string         `db:"api_key_id" json:"api_key_id"`
	ActorKind      string          `db:"actor_kind" json:"actor_kind"`
	ClientType     *string         `db:"client_type" json:"client_type"`
	ClientVersion  *string         `db:"client_version" json:"client_version"`
	AgentModel     *string         `db:"agent_model" json:"agent_model"`
	AgentSessionID *string         `db:"agent_session_id" json:"agent_session_id"`
	Trigger        *string         `db:"trigger" json:"trigger"`
	BatchID        *string         `db:"batch_id" json:"batch_id"`
	CodeCommit     *string         `db:"code_commit" json:"code_commit"`
	SourcePath     *string         `db:"source_path" json:"source_path"`
	Confidence     *string         `db:"confidence" json:"confidence"`
	Metadata       json.RawMessage `db:"metadata" json:"metadata"`
	CreatedAt      time.Time       `db:"created_at" json:"created_at"`
}

type Edge struct {
	ID         string    `db:"id" json:"id"`
	ProjectID  string    `db:"project_id" json:"project_id"`
	SourceID   string    `db:"source_id" json:"source_id"`
	TargetID   string    `db:"target_id" json:"target_id"`
	EdgeType   string    `db:"edge_type" json:"edge_type"`
	Label      *string   `db:"label" json:"label"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	SourcePort string    `db:"source_port" json:"source_port"`
	TargetPort string    `db:"target_port" json:"target_port"`
	Waypoints  []byte    `db:"waypoints" json:"waypoints"`
}

type IdempotencyKey struct {
	Key        string    `db:"key" json:"key"`
	ApiKeyID   string    `db:"api_key_id" json:"api_key_id"`
	Method     string    `db:"method" json:"method"`
	Path       string    `db:"path" json:"path"`
	StatusCode int32     `db:"status_code" json:"status_code"`
	Response   []byte    `db:"response" json:"response"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	ExpiresAt  time.Time `db:"expires_at" json:"expires_at"`
}

type Node struct {
	ID                    string          `db:"id" json:"id"`
	ProjectID             string          `db:"project_id" json:"project_id"`
	Type                  string          `db:"type" json:"type"`
	Title                 string          `db:"title" json:"title"`
	Description           *string         `db:"description" json:"description"`
	Status                string          `db:"status" json:"status"`
	AssigneeID            *string         `db:"assignee_id" json:"assignee_id"`
	Tags                  []string        `db:"tags" json:"tags"`
	Metadata              json.RawMessage `db:"metadata" json:"metadata"`
	ParentID              *string         `db:"parent_id" json:"parent_id"`
	PositionX             float64         `db:"position_x" json:"position_x"`
	PositionY             float64         `db:"position_y" json:"position_y"`
	Width                 *float64        `db:"width" json:"width"`
	Height                *float64        `db:"height" json:"height"`
	CreatedAt             time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time       `db:"updated_at" json:"updated_at"`
	DescriptionSource     string          `db:"description_source" json:"description_source"`
	DescriptionAuthoredBy *string         `db:"description_authored_by" json:"description_authored_by"`
	DescriptionAuthoredAt *time.Time      `db:"description_authored_at" json:"description_authored_at"`
	DescriptionAgentModel *string         `db:"description_agent_model" json:"description_agent_model"`
	LastVerifiedAt        *time.Time      `db:"last_verified_at" json:"last_verified_at"`
	LastVerifiedBy        *string         `db:"last_verified_by" json:"last_verified_by"`
	LastVerifiedCommit    *string         `db:"last_verified_commit" json:"last_verified_commit"`
	FieldProvenance       json.RawMessage `db:"field_provenance" json:"field_provenance"`
	CreatedBy             *string         `db:"created_by" json:"created_by"`
}

type NodeHistory struct {
	ID        string      `db:"id" json:"id"`
	NodeID    string      `db:"node_id" json:"node_id"`
	ProjectID string      `db:"project_id" json:"project_id"`
	UserID    string      `db:"user_id" json:"user_id"`
	Action    interface{} `db:"action" json:"action"`
	FieldName *string     `db:"field_name" json:"field_name"`
	OldValue  *string     `db:"old_value" json:"old_value"`
	NewValue  *string     `db:"new_value" json:"new_value"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
}

type NodeSuggestion struct {
	ID             string     `db:"id" json:"id"`
	ProjectID      string     `db:"project_id" json:"project_id"`
	NodeID         string     `db:"node_id" json:"node_id"`
	FieldName      string     `db:"field_name" json:"field_name"`
	ProposedValue  string     `db:"proposed_value" json:"proposed_value"`
	CurrentValue   *string    `db:"current_value" json:"current_value"`
	Rationale      *string    `db:"rationale" json:"rationale"`
	Evidence       []byte     `db:"evidence" json:"evidence"`
	ProposedBy     string     `db:"proposed_by" json:"proposed_by"`
	AgentModel     *string    `db:"agent_model" json:"agent_model"`
	AgentSessionID *string    `db:"agent_session_id" json:"agent_session_id"`
	Status         string     `db:"status" json:"status"`
	DecidedBy      *string    `db:"decided_by" json:"decided_by"`
	DecidedAt      *time.Time `db:"decided_at" json:"decided_at"`
	DecidedReason  *string    `db:"decided_reason" json:"decided_reason"`
	CreatedAt      time.Time  `db:"created_at" json:"created_at"`
}

type Project struct {
	ID             string    `db:"id" json:"id"`
	TeamID         string    `db:"team_id" json:"team_id"`
	Name           string    `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
	LinkSharing    string    `db:"link_sharing" json:"link_sharing"`
	ShareToken     *string   `db:"share_token" json:"share_token"`
	ShareTokenHash *string   `db:"share_token_hash" json:"share_token_hash"`
}

type ProjectMember struct {
	ID        string    `db:"id" json:"id"`
	ProjectID string    `db:"project_id" json:"project_id"`
	UserID    string    `db:"user_id" json:"user_id"`
	Role      string    `db:"role" json:"role"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type SchemaMigration struct {
	Version   int32     `db:"version" json:"version"`
	AppliedAt time.Time `db:"applied_at" json:"applied_at"`
}

type Session struct {
	ID        string    `db:"id" json:"id"`
	UserID    string    `db:"user_id" json:"user_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Team struct {
	ID        string    `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Slug      string    `db:"slug" json:"slug"`
	CreatedBy string    `db:"created_by" json:"created_by"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type TeamMember struct {
	ID       string    `db:"id" json:"id"`
	TeamID   string    `db:"team_id" json:"team_id"`
	UserID   string    `db:"user_id" json:"user_id"`
	Role     string    `db:"role" json:"role"`
	JoinedAt time.Time `db:"joined_at" json:"joined_at"`
}

type User struct {
	ID           string    `db:"id" json:"id"`
	Email        string    `db:"email" json:"email"`
	DisplayName  string    `db:"display_name" json:"display_name"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}
