// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const nodeBatchUpdateStatus = `-- name: NodeBatchUpdateStatus :exec
UPDATE nodes
SET status = $1, updated_at = now()
WHERE id = ANY($2::uuid[]) AND project_id = $3
`

type NodeBatchUpdateStatusParams struct {
	Status    string   `db:"status" json:"status"`
	NodeIds   []string `db:"node_ids" json:"node_ids"`
	ProjectID string   `db:"project_id" json:"project_id"`
}

func (q *Queries) NodeBatchUpdateStatus(ctx context.Context, arg NodeBatchUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, nodeBatchUpdateStatus, arg.Status, arg.NodeIds, arg.ProjectID)
	return err
}

const nodeCreate = `-- name: NodeCreate :one

INSERT INTO nodes (
  project_id, type, title, description, status, assignee_id, tags,
  parent_id, position_x, position_y, width, height, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, project_id, type, title, description, status, assignee_id, tags,
  metadata, parent_id, position_x, position_y, width, height,
  created_at, updated_at,
  description_source, description_authored_by, description_authored_at,
  description_agent_model,
  last_verified_at, last_verified_by, last_verified_commit, field_provenance,
  created_by
`

type NodeCreateParams struct {
	ProjectID   string   `db:"project_id" json:"project_id"`
	Type        string   `db:"type" json:"type"`
	Title       string   `db:"title" json:"title"`
	Description *string  `db:"description" json:"description"`
	Status      string   `db:"status" json:"status"`
	AssigneeID  *string  `db:"assignee_id" json:"assignee_id"`
	Tags        []string `db:"tags" json:"tags"`
	ParentID    *string  `db:"parent_id" json:"parent_id"`
	PositionX   float64  `db:"position_x" json:"position_x"`
	PositionY   float64  `db:"position_y" json:"position_y"`
	Width       *float64 `db:"width" json:"width"`
	Height      *float64 `db:"height" json:"height"`
	CreatedBy   *string  `db:"created_by" json:"created_by"`
}

// ============================================================================
// Node static queries (sqlc-generated)
//
// Dynamic queries (FindByProjectID with optional filters, Update with dynamic
// setClauses, FindByProjectIDPaginated, BatchUpdatePositions multi-row) stay
// as hand-written pgx in internal/repository/node.go.
// ============================================================================
func (q *Queries) NodeCreate(ctx context.Context, arg NodeCreateParams) (Node, error) {
	row := q.db.QueryRow(ctx, nodeCreate,
		arg.ProjectID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.AssigneeID,
		arg.Tags,
		arg.ParentID,
		arg.PositionX,
		arg.PositionY,
		arg.Width,
		arg.Height,
		arg.CreatedBy,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.Tags,
		&i.Metadata,
		&i.ParentID,
		&i.PositionX,
		&i.PositionY,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DescriptionSource,
		&i.DescriptionAuthoredBy,
		&i.DescriptionAuthoredAt,
		&i.DescriptionAgentModel,
		&i.LastVerifiedAt,
		&i.LastVerifiedBy,
		&i.LastVerifiedCommit,
		&i.FieldProvenance,
		&i.CreatedBy,
	)
	return i, err
}

const nodeDeleteByID = `-- name: NodeDeleteByID :exec
DELETE FROM nodes WHERE id = $1 AND project_id = $2
`

type NodeDeleteByIDParams struct {
	ID        string `db:"id" json:"id"`
	ProjectID string `db:"project_id" json:"project_id"`
}

func (q *Queries) NodeDeleteByID(ctx context.Context, arg NodeDeleteByIDParams) error {
	_, err := q.db.Exec(ctx, nodeDeleteByID, arg.ID, arg.ProjectID)
	return err
}

const nodeDeleteByIDs = `-- name: NodeDeleteByIDs :exec
DELETE FROM nodes
WHERE id = ANY($1::uuid[]) AND project_id = $2
`

type NodeDeleteByIDsParams struct {
	NodeIds   []string `db:"node_ids" json:"node_ids"`
	ProjectID string   `db:"project_id" json:"project_id"`
}

func (q *Queries) NodeDeleteByIDs(ctx context.Context, arg NodeDeleteByIDsParams) error {
	_, err := q.db.Exec(ctx, nodeDeleteByIDs, arg.NodeIds, arg.ProjectID)
	return err
}

const nodeFindByID = `-- name: NodeFindByID :one
SELECT n.id, n.project_id, n.type, n.title, n.description, n.status,
       n.assignee_id, n.tags, n.metadata, n.parent_id,
       n.position_x, n.position_y, n.width, n.height,
       n.created_at, n.updated_at,
       n.description_source, n.description_authored_by,
       n.description_authored_at, n.description_agent_model,
       n.last_verified_at, n.last_verified_by, n.last_verified_commit,
       n.field_provenance, n.created_by,
       COALESCE(u.email, '')::text AS creator_email
FROM nodes n
LEFT JOIN users u ON u.id = n.created_by
WHERE n.id = $1 AND n.project_id = $2
`

type NodeFindByIDParams struct {
	ID        string `db:"id" json:"id"`
	ProjectID string `db:"project_id" json:"project_id"`
}

type NodeFindByIDRow struct {
	ID                    string          `db:"id" json:"id"`
	ProjectID             string          `db:"project_id" json:"project_id"`
	Type                  string          `db:"type" json:"type"`
	Title                 string          `db:"title" json:"title"`
	Description           *string         `db:"description" json:"description"`
	Status                string          `db:"status" json:"status"`
	AssigneeID            *string         `db:"assignee_id" json:"assignee_id"`
	Tags                  []string        `db:"tags" json:"tags"`
	Metadata              json.RawMessage `db:"metadata" json:"metadata"`
	ParentID              *string         `db:"parent_id" json:"parent_id"`
	PositionX             float64         `db:"position_x" json:"position_x"`
	PositionY             float64         `db:"position_y" json:"position_y"`
	Width                 *float64        `db:"width" json:"width"`
	Height                *float64        `db:"height" json:"height"`
	CreatedAt             time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time       `db:"updated_at" json:"updated_at"`
	DescriptionSource     string          `db:"description_source" json:"description_source"`
	DescriptionAuthoredBy *string         `db:"description_authored_by" json:"description_authored_by"`
	DescriptionAuthoredAt *time.Time      `db:"description_authored_at" json:"description_authored_at"`
	DescriptionAgentModel *string         `db:"description_agent_model" json:"description_agent_model"`
	LastVerifiedAt        *time.Time      `db:"last_verified_at" json:"last_verified_at"`
	LastVerifiedBy        *string         `db:"last_verified_by" json:"last_verified_by"`
	LastVerifiedCommit    *string         `db:"last_verified_commit" json:"last_verified_commit"`
	FieldProvenance       json.RawMessage `db:"field_provenance" json:"field_provenance"`
	CreatedBy             *string         `db:"created_by" json:"created_by"`
	CreatorEmail          string          `db:"creator_email" json:"creator_email"`
}

func (q *Queries) NodeFindByID(ctx context.Context, arg NodeFindByIDParams) (NodeFindByIDRow, error) {
	row := q.db.QueryRow(ctx, nodeFindByID, arg.ID, arg.ProjectID)
	var i NodeFindByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.AssigneeID,
		&i.Tags,
		&i.Metadata,
		&i.ParentID,
		&i.PositionX,
		&i.PositionY,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DescriptionSource,
		&i.DescriptionAuthoredBy,
		&i.DescriptionAuthoredAt,
		&i.DescriptionAgentModel,
		&i.LastVerifiedAt,
		&i.LastVerifiedBy,
		&i.LastVerifiedCommit,
		&i.FieldProvenance,
		&i.CreatedBy,
		&i.CreatorEmail,
	)
	return i, err
}

const nodeFindByIDs = `-- name: NodeFindByIDs :many
SELECT n.id, n.project_id, n.type, n.title, n.description, n.status,
       n.assignee_id, n.tags, n.metadata, n.parent_id,
       n.position_x, n.position_y, n.width, n.height,
       n.created_at, n.updated_at,
       n.description_source, n.description_authored_by,
       n.description_authored_at, n.description_agent_model,
       n.last_verified_at, n.last_verified_by, n.last_verified_commit,
       n.field_provenance, n.created_by,
       COALESCE(u.email, '')::text AS creator_email
FROM nodes n
LEFT JOIN users u ON u.id = n.created_by
WHERE n.id = ANY($1::uuid[])
`

type NodeFindByIDsRow struct {
	ID                    string          `db:"id" json:"id"`
	ProjectID             string          `db:"project_id" json:"project_id"`
	Type                  string          `db:"type" json:"type"`
	Title                 string          `db:"title" json:"title"`
	Description           *string         `db:"description" json:"description"`
	Status                string          `db:"status" json:"status"`
	AssigneeID            *string         `db:"assignee_id" json:"assignee_id"`
	Tags                  []string        `db:"tags" json:"tags"`
	Metadata              json.RawMessage `db:"metadata" json:"metadata"`
	ParentID              *string         `db:"parent_id" json:"parent_id"`
	PositionX             float64         `db:"position_x" json:"position_x"`
	PositionY             float64         `db:"position_y" json:"position_y"`
	Width                 *float64        `db:"width" json:"width"`
	Height                *float64        `db:"height" json:"height"`
	CreatedAt             time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time       `db:"updated_at" json:"updated_at"`
	DescriptionSource     string          `db:"description_source" json:"description_source"`
	DescriptionAuthoredBy *string         `db:"description_authored_by" json:"description_authored_by"`
	DescriptionAuthoredAt *time.Time      `db:"description_authored_at" json:"description_authored_at"`
	DescriptionAgentModel *string         `db:"description_agent_model" json:"description_agent_model"`
	LastVerifiedAt        *time.Time      `db:"last_verified_at" json:"last_verified_at"`
	LastVerifiedBy        *string         `db:"last_verified_by" json:"last_verified_by"`
	LastVerifiedCommit    *string         `db:"last_verified_commit" json:"last_verified_commit"`
	FieldProvenance       json.RawMessage `db:"field_provenance" json:"field_provenance"`
	CreatedBy             *string         `db:"created_by" json:"created_by"`
	CreatorEmail          string          `db:"creator_email" json:"creator_email"`
}

func (q *Queries) NodeFindByIDs(ctx context.Context, nodeIds []string) ([]NodeFindByIDsRow, error) {
	rows, err := q.db.Query(ctx, nodeFindByIDs, nodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeFindByIDsRow{}
	for rows.Next() {
		var i NodeFindByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssigneeID,
			&i.Tags,
			&i.Metadata,
			&i.ParentID,
			&i.PositionX,
			&i.PositionY,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DescriptionSource,
			&i.DescriptionAuthoredBy,
			&i.DescriptionAuthoredAt,
			&i.DescriptionAgentModel,
			&i.LastVerifiedAt,
			&i.LastVerifiedBy,
			&i.LastVerifiedCommit,
			&i.FieldProvenance,
			&i.CreatedBy,
			&i.CreatorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeFindByProjectIDSimple = `-- name: NodeFindByProjectIDSimple :many
SELECT n.id, n.project_id, n.type, n.title, n.description, n.status,
       n.assignee_id, n.tags, n.metadata, n.parent_id,
       n.position_x, n.position_y, n.width, n.height,
       n.created_at, n.updated_at,
       n.description_source, n.description_authored_by,
       n.description_authored_at, n.description_agent_model,
       n.last_verified_at, n.last_verified_by, n.last_verified_commit,
       n.field_provenance, n.created_by,
       COALESCE(u.email, '')::text AS creator_email
FROM nodes n
LEFT JOIN users u ON u.id = n.created_by
WHERE n.project_id = $1
`

type NodeFindByProjectIDSimpleRow struct {
	ID                    string          `db:"id" json:"id"`
	ProjectID             string          `db:"project_id" json:"project_id"`
	Type                  string          `db:"type" json:"type"`
	Title                 string          `db:"title" json:"title"`
	Description           *string         `db:"description" json:"description"`
	Status                string          `db:"status" json:"status"`
	AssigneeID            *string         `db:"assignee_id" json:"assignee_id"`
	Tags                  []string        `db:"tags" json:"tags"`
	Metadata              json.RawMessage `db:"metadata" json:"metadata"`
	ParentID              *string         `db:"parent_id" json:"parent_id"`
	PositionX             float64         `db:"position_x" json:"position_x"`
	PositionY             float64         `db:"position_y" json:"position_y"`
	Width                 *float64        `db:"width" json:"width"`
	Height                *float64        `db:"height" json:"height"`
	CreatedAt             time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time       `db:"updated_at" json:"updated_at"`
	DescriptionSource     string          `db:"description_source" json:"description_source"`
	DescriptionAuthoredBy *string         `db:"description_authored_by" json:"description_authored_by"`
	DescriptionAuthoredAt *time.Time      `db:"description_authored_at" json:"description_authored_at"`
	DescriptionAgentModel *string         `db:"description_agent_model" json:"description_agent_model"`
	LastVerifiedAt        *time.Time      `db:"last_verified_at" json:"last_verified_at"`
	LastVerifiedBy        *string         `db:"last_verified_by" json:"last_verified_by"`
	LastVerifiedCommit    *string         `db:"last_verified_commit" json:"last_verified_commit"`
	FieldProvenance       json.RawMessage `db:"field_provenance" json:"field_provenance"`
	CreatedBy             *string         `db:"created_by" json:"created_by"`
	CreatorEmail          string          `db:"creator_email" json:"creator_email"`
}

// Used when no type/status filter is requested.
func (q *Queries) NodeFindByProjectIDSimple(ctx context.Context, projectID string) ([]NodeFindByProjectIDSimpleRow, error) {
	rows, err := q.db.Query(ctx, nodeFindByProjectIDSimple, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeFindByProjectIDSimpleRow{}
	for rows.Next() {
		var i NodeFindByProjectIDSimpleRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssigneeID,
			&i.Tags,
			&i.Metadata,
			&i.ParentID,
			&i.PositionX,
			&i.PositionY,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DescriptionSource,
			&i.DescriptionAuthoredBy,
			&i.DescriptionAuthoredAt,
			&i.DescriptionAgentModel,
			&i.LastVerifiedAt,
			&i.LastVerifiedBy,
			&i.LastVerifiedCommit,
			&i.FieldProvenance,
			&i.CreatedBy,
			&i.CreatorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeFindChangedSince = `-- name: NodeFindChangedSince :many
SELECT n.id, n.project_id, n.type, n.title, n.description, n.status,
       n.assignee_id, n.tags, n.metadata, n.parent_id,
       n.position_x, n.position_y, n.width, n.height,
       n.created_at, n.updated_at,
       n.description_source, n.description_authored_by,
       n.description_authored_at, n.description_agent_model,
       n.last_verified_at, n.last_verified_by, n.last_verified_commit,
       n.field_provenance, n.created_by,
       COALESCE(u.email, '')::text AS creator_email
FROM nodes n
LEFT JOIN users u ON u.id = n.created_by
WHERE n.project_id = $1 AND n.updated_at >= $2
`

type NodeFindChangedSinceParams struct {
	ProjectID string    `db:"project_id" json:"project_id"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type NodeFindChangedSinceRow struct {
	ID                    string          `db:"id" json:"id"`
	ProjectID             string          `db:"project_id" json:"project_id"`
	Type                  string          `db:"type" json:"type"`
	Title                 string          `db:"title" json:"title"`
	Description           *string         `db:"description" json:"description"`
	Status                string          `db:"status" json:"status"`
	AssigneeID            *string         `db:"assignee_id" json:"assignee_id"`
	Tags                  []string        `db:"tags" json:"tags"`
	Metadata              json.RawMessage `db:"metadata" json:"metadata"`
	ParentID              *string         `db:"parent_id" json:"parent_id"`
	PositionX             float64         `db:"position_x" json:"position_x"`
	PositionY             float64         `db:"position_y" json:"position_y"`
	Width                 *float64        `db:"width" json:"width"`
	Height                *float64        `db:"height" json:"height"`
	CreatedAt             time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time       `db:"updated_at" json:"updated_at"`
	DescriptionSource     string          `db:"description_source" json:"description_source"`
	DescriptionAuthoredBy *string         `db:"description_authored_by" json:"description_authored_by"`
	DescriptionAuthoredAt *time.Time      `db:"description_authored_at" json:"description_authored_at"`
	DescriptionAgentModel *string         `db:"description_agent_model" json:"description_agent_model"`
	LastVerifiedAt        *time.Time      `db:"last_verified_at" json:"last_verified_at"`
	LastVerifiedBy        *string         `db:"last_verified_by" json:"last_verified_by"`
	LastVerifiedCommit    *string         `db:"last_verified_commit" json:"last_verified_commit"`
	FieldProvenance       json.RawMessage `db:"field_provenance" json:"field_provenance"`
	CreatedBy             *string         `db:"created_by" json:"created_by"`
	CreatorEmail          string          `db:"creator_email" json:"creator_email"`
}

func (q *Queries) NodeFindChangedSince(ctx context.Context, arg NodeFindChangedSinceParams) ([]NodeFindChangedSinceRow, error) {
	rows, err := q.db.Query(ctx, nodeFindChangedSince, arg.ProjectID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeFindChangedSinceRow{}
	for rows.Next() {
		var i NodeFindChangedSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssigneeID,
			&i.Tags,
			&i.Metadata,
			&i.ParentID,
			&i.PositionX,
			&i.PositionY,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DescriptionSource,
			&i.DescriptionAuthoredBy,
			&i.DescriptionAuthoredAt,
			&i.DescriptionAgentModel,
			&i.LastVerifiedAt,
			&i.LastVerifiedBy,
			&i.LastVerifiedCommit,
			&i.FieldProvenance,
			&i.CreatedBy,
			&i.CreatorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeFindFailOrBug = `-- name: NodeFindFailOrBug :many
SELECT n.id, n.project_id, n.type, n.title, n.description, n.status,
       n.assignee_id, n.tags, n.metadata, n.parent_id,
       n.position_x, n.position_y, n.width, n.height,
       n.created_at, n.updated_at,
       n.description_source, n.description_authored_by,
       n.description_authored_at, n.description_agent_model,
       n.last_verified_at, n.last_verified_by, n.last_verified_commit,
       n.field_provenance, n.created_by,
       COALESCE(u.email, '')::text AS creator_email
FROM nodes n
LEFT JOIN users u ON u.id = n.created_by
WHERE n.project_id = $1 AND (n.status = 'FAIL' OR n.type = 'BUG')
`

type NodeFindFailOrBugRow struct {
	ID                    string          `db:"id" json:"id"`
	ProjectID             string          `db:"project_id" json:"project_id"`
	Type                  string          `db:"type" json:"type"`
	Title                 string          `db:"title" json:"title"`
	Description           *string         `db:"description" json:"description"`
	Status                string          `db:"status" json:"status"`
	AssigneeID            *string         `db:"assignee_id" json:"assignee_id"`
	Tags                  []string        `db:"tags" json:"tags"`
	Metadata              json.RawMessage `db:"metadata" json:"metadata"`
	ParentID              *string         `db:"parent_id" json:"parent_id"`
	PositionX             float64         `db:"position_x" json:"position_x"`
	PositionY             float64         `db:"position_y" json:"position_y"`
	Width                 *float64        `db:"width" json:"width"`
	Height                *float64        `db:"height" json:"height"`
	CreatedAt             time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time       `db:"updated_at" json:"updated_at"`
	DescriptionSource     string          `db:"description_source" json:"description_source"`
	DescriptionAuthoredBy *string         `db:"description_authored_by" json:"description_authored_by"`
	DescriptionAuthoredAt *time.Time      `db:"description_authored_at" json:"description_authored_at"`
	DescriptionAgentModel *string         `db:"description_agent_model" json:"description_agent_model"`
	LastVerifiedAt        *time.Time      `db:"last_verified_at" json:"last_verified_at"`
	LastVerifiedBy        *string         `db:"last_verified_by" json:"last_verified_by"`
	LastVerifiedCommit    *string         `db:"last_verified_commit" json:"last_verified_commit"`
	FieldProvenance       json.RawMessage `db:"field_provenance" json:"field_provenance"`
	CreatedBy             *string         `db:"created_by" json:"created_by"`
	CreatorEmail          string          `db:"creator_email" json:"creator_email"`
}

func (q *Queries) NodeFindFailOrBug(ctx context.Context, projectID string) ([]NodeFindFailOrBugRow, error) {
	rows, err := q.db.Query(ctx, nodeFindFailOrBug, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeFindFailOrBugRow{}
	for rows.Next() {
		var i NodeFindFailOrBugRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.AssigneeID,
			&i.Tags,
			&i.Metadata,
			&i.ParentID,
			&i.PositionX,
			&i.PositionY,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DescriptionSource,
			&i.DescriptionAuthoredBy,
			&i.DescriptionAuthoredAt,
			&i.DescriptionAgentModel,
			&i.LastVerifiedAt,
			&i.LastVerifiedBy,
			&i.LastVerifiedCommit,
			&i.FieldProvenance,
			&i.CreatedBy,
			&i.CreatorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeMarkVerified = `-- name: NodeMarkVerified :execrows
UPDATE nodes
SET last_verified_at = now(),
    last_verified_by = $1,
    last_verified_commit = $2,
    updated_at = now()
WHERE id = $3 AND project_id = $4
`

type NodeMarkVerifiedParams struct {
	LastVerifiedBy     *string `db:"last_verified_by" json:"last_verified_by"`
	LastVerifiedCommit *string `db:"last_verified_commit" json:"last_verified_commit"`
	ID                 string  `db:"id" json:"id"`
	ProjectID          string  `db:"project_id" json:"project_id"`
}

func (q *Queries) NodeMarkVerified(ctx context.Context, arg NodeMarkVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, nodeMarkVerified,
		arg.LastVerifiedBy,
		arg.LastVerifiedCommit,
		arg.ID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nodeUnparentChildren = `-- name: NodeUnparentChildren :exec
UPDATE nodes
SET parent_id = NULL, updated_at = now()
WHERE parent_id = ANY($1::uuid[]) AND project_id = $2
`

type NodeUnparentChildrenParams struct {
	ParentIds []string `db:"parent_ids" json:"parent_ids"`
	ProjectID string   `db:"project_id" json:"project_id"`
}

// Used by Delete and BatchDelete to detach children before removing parent.
func (q *Queries) NodeUnparentChildren(ctx context.Context, arg NodeUnparentChildrenParams) error {
	_, err := q.db.Exec(ctx, nodeUnparentChildren, arg.ParentIds, arg.ProjectID)
	return err
}

const nodeUpdateDescriptionProvenance = `-- name: NodeUpdateDescriptionProvenance :exec
UPDATE nodes
SET description_source = $1,
    description_authored_by = $2,
    description_authored_at = now(),
    description_agent_model = $3
WHERE id = $4
`

type NodeUpdateDescriptionProvenanceParams struct {
	DescriptionSource     string  `db:"description_source" json:"description_source"`
	DescriptionAuthoredBy *string `db:"description_authored_by" json:"description_authored_by"`
	DescriptionAgentModel *string `db:"description_agent_model" json:"description_agent_model"`
	ID                    string  `db:"id" json:"id"`
}

func (q *Queries) NodeUpdateDescriptionProvenance(ctx context.Context, arg NodeUpdateDescriptionProvenanceParams) error {
	_, err := q.db.Exec(ctx, nodeUpdateDescriptionProvenance,
		arg.DescriptionSource,
		arg.DescriptionAuthoredBy,
		arg.DescriptionAgentModel,
		arg.ID,
	)
	return err
}

const nodeUpdateStatus = `-- name: NodeUpdateStatus :exec
UPDATE nodes SET status = $1, updated_at = now() WHERE id = $2
`

type NodeUpdateStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) NodeUpdateStatus(ctx context.Context, arg NodeUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, nodeUpdateStatus, arg.Status, arg.ID)
	return err
}
