// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_member.sql

package dbgen

import (
	"context"
)

const projectMemberAdd = `-- name: ProjectMemberAdd :exec
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
`

type ProjectMemberAddParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	UserID    string `db:"user_id" json:"user_id"`
	Role      string `db:"role" json:"role"`
}

func (q *Queries) ProjectMemberAdd(ctx context.Context, arg ProjectMemberAddParams) error {
	_, err := q.db.Exec(ctx, projectMemberAdd, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const projectMemberGetRole = `-- name: ProjectMemberGetRole :one

SELECT role FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type ProjectMemberGetRoleParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	UserID    string `db:"user_id" json:"user_id"`
}

// ============================================================================
// ProjectMember static queries (sqlc-generated)
//
// Dynamic queries:
//
//	ListWithUsers (JOIN projects_members + users producing flat
//	ProjectMemberWithUser) stays hand-written pgx — sqlc can't split one row
//	into two destination structs cleanly.
//
// ============================================================================
func (q *Queries) ProjectMemberGetRole(ctx context.Context, arg ProjectMemberGetRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, projectMemberGetRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const projectMemberRemove = `-- name: ProjectMemberRemove :execrows
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type ProjectMemberRemoveParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	UserID    string `db:"user_id" json:"user_id"`
}

func (q *Queries) ProjectMemberRemove(ctx context.Context, arg ProjectMemberRemoveParams) (int64, error) {
	result, err := q.db.Exec(ctx, projectMemberRemove, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const projectMemberUpdateRole = `-- name: ProjectMemberUpdateRole :execrows
UPDATE project_members
SET role = $3
WHERE project_id = $1 AND user_id = $2
`

type ProjectMemberUpdateRoleParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	UserID    string `db:"user_id" json:"user_id"`
	Role      string `db:"role" json:"role"`
}

func (q *Queries) ProjectMemberUpdateRole(ctx context.Context, arg ProjectMemberUpdateRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, projectMemberUpdateRole, arg.ProjectID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
