// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_tag.sql

package dbgen

import (
	"context"
)

const projectTagDelete = `-- name: ProjectTagDelete :execrows
DELETE FROM project_tags WHERE project_id = $1 AND tag = $2
`

type ProjectTagDeleteParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Tag       string `db:"tag" json:"tag"`
}

func (q *Queries) ProjectTagDelete(ctx context.Context, arg ProjectTagDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, projectTagDelete, arg.ProjectID, arg.Tag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const projectTagList = `-- name: ProjectTagList :many
SELECT project_id, tag, color, description, created_at, created_by
FROM project_tags
WHERE project_id = $1
ORDER BY tag ASC
`

func (q *Queries) ProjectTagList(ctx context.Context, projectID string) ([]ProjectTag, error) {
	rows, err := q.db.Query(ctx, projectTagList, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTag{}
	for rows.Next() {
		var i ProjectTag
		if err := rows.Scan(
			&i.ProjectID,
			&i.Tag,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectTagUpsert = `-- name: ProjectTagUpsert :one

INSERT INTO project_tags (project_id, tag, color, description, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, tag) DO UPDATE
   SET color       = EXCLUDED.color,
       description = EXCLUDED.description
RETURNING project_id, tag, color, description, created_at, created_by
`

type ProjectTagUpsertParams struct {
	ProjectID   string  `db:"project_id" json:"project_id"`
	Tag         string  `db:"tag" json:"tag"`
	Color       *string `db:"color" json:"color"`
	Description *string `db:"description" json:"description"`
	CreatedBy   *string `db:"created_by" json:"created_by"`
}

// ============================================================================
// Project tag queries (v0.6.0 B-3). Canonical metadata (color, description)
// for tags used across a project. nodes.tags TEXT[] is still the primary
// storage — project_tags augments it for autocomplete and consistent styling.
// ============================================================================
func (q *Queries) ProjectTagUpsert(ctx context.Context, arg ProjectTagUpsertParams) (ProjectTag, error) {
	row := q.db.QueryRow(ctx, projectTagUpsert,
		arg.ProjectID,
		arg.Tag,
		arg.Color,
		arg.Description,
		arg.CreatedBy,
	)
	var i ProjectTag
	err := row.Scan(
		&i.ProjectID,
		&i.Tag,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
