// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package dbgen

import (
	"context"
	"time"
)

const projectCreate = `-- name: ProjectCreate :one

INSERT INTO projects (team_id, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, name, description, created_by, link_sharing, share_token, share_token_hash, created_at, updated_at
`

type ProjectCreateParams struct {
	TeamID      string  `db:"team_id" json:"team_id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	CreatedBy   string  `db:"created_by" json:"created_by"`
}

type ProjectCreateRow struct {
	ID             string    `db:"id" json:"id"`
	TeamID         string    `db:"team_id" json:"team_id"`
	Name           string    `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	LinkSharing    string    `db:"link_sharing" json:"link_sharing"`
	ShareToken     *string   `db:"share_token" json:"share_token"`
	ShareTokenHash *string   `db:"share_token_hash" json:"share_token_hash"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

// ============================================================================
// Project static queries (sqlc-generated)
//
// Dynamic queries:
//
//	GraphUpdatedAt (multi-subquery GREATEST across 3 tables) stays hand-written.
//
// ============================================================================
func (q *Queries) ProjectCreate(ctx context.Context, arg ProjectCreateParams) (ProjectCreateRow, error) {
	row := q.db.QueryRow(ctx, projectCreate,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i ProjectCreateRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.LinkSharing,
		&i.ShareToken,
		&i.ShareTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectDelete = `-- name: ProjectDelete :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) ProjectDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, projectDelete, id)
	return err
}

const projectFindByID = `-- name: ProjectFindByID :one
SELECT id, team_id, name, description, created_by, link_sharing, share_token, share_token_hash, created_at, updated_at
FROM projects
WHERE id = $1
`

type ProjectFindByIDRow struct {
	ID             string    `db:"id" json:"id"`
	TeamID         string    `db:"team_id" json:"team_id"`
	Name           string    `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	LinkSharing    string    `db:"link_sharing" json:"link_sharing"`
	ShareToken     *string   `db:"share_token" json:"share_token"`
	ShareTokenHash *string   `db:"share_token_hash" json:"share_token_hash"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ProjectFindByID(ctx context.Context, id string) (ProjectFindByIDRow, error) {
	row := q.db.QueryRow(ctx, projectFindByID, id)
	var i ProjectFindByIDRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.LinkSharing,
		&i.ShareToken,
		&i.ShareTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectFindByShareToken = `-- name: ProjectFindByShareToken :one
SELECT id, team_id, name, description, created_by, link_sharing, share_token, share_token_hash, created_at, updated_at
FROM projects
WHERE share_token_hash = $1 AND link_sharing != 'off'
`

type ProjectFindByShareTokenRow struct {
	ID             string    `db:"id" json:"id"`
	TeamID         string    `db:"team_id" json:"team_id"`
	Name           string    `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	LinkSharing    string    `db:"link_sharing" json:"link_sharing"`
	ShareToken     *string   `db:"share_token" json:"share_token"`
	ShareTokenHash *string   `db:"share_token_hash" json:"share_token_hash"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ProjectFindByShareToken(ctx context.Context, shareTokenHash *string) (ProjectFindByShareTokenRow, error) {
	row := q.db.QueryRow(ctx, projectFindByShareToken, shareTokenHash)
	var i ProjectFindByShareTokenRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.LinkSharing,
		&i.ShareToken,
		&i.ShareTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectFindByTeamID = `-- name: ProjectFindByTeamID :many
SELECT id, team_id, name, description, created_by, link_sharing, share_token, share_token_hash, created_at, updated_at
FROM projects
WHERE team_id = $1
`

type ProjectFindByTeamIDRow struct {
	ID             string    `db:"id" json:"id"`
	TeamID         string    `db:"team_id" json:"team_id"`
	Name           string    `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	LinkSharing    string    `db:"link_sharing" json:"link_sharing"`
	ShareToken     *string   `db:"share_token" json:"share_token"`
	ShareTokenHash *string   `db:"share_token_hash" json:"share_token_hash"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ProjectFindByTeamID(ctx context.Context, teamID string) ([]ProjectFindByTeamIDRow, error) {
	rows, err := q.db.Query(ctx, projectFindByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectFindByTeamIDRow{}
	for rows.Next() {
		var i ProjectFindByTeamIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.LinkSharing,
			&i.ShareToken,
			&i.ShareTokenHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectFindByTeamIDs = `-- name: ProjectFindByTeamIDs :many
SELECT id, team_id, name, description, created_by, link_sharing, share_token, share_token_hash, created_at, updated_at
FROM projects
WHERE team_id = ANY($1::uuid[])
`

type ProjectFindByTeamIDsRow struct {
	ID             string    `db:"id" json:"id"`
	TeamID         string    `db:"team_id" json:"team_id"`
	Name           string    `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	LinkSharing    string    `db:"link_sharing" json:"link_sharing"`
	ShareToken     *string   `db:"share_token" json:"share_token"`
	ShareTokenHash *string   `db:"share_token_hash" json:"share_token_hash"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ProjectFindByTeamIDs(ctx context.Context, teamIds []string) ([]ProjectFindByTeamIDsRow, error) {
	rows, err := q.db.Query(ctx, projectFindByTeamIDs, teamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectFindByTeamIDsRow{}
	for rows.Next() {
		var i ProjectFindByTeamIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.LinkSharing,
			&i.ShareToken,
			&i.ShareTokenHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectUpdate = `-- name: ProjectUpdate :one
UPDATE projects
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    updated_at  = now()
WHERE id = $3
RETURNING id, team_id, name, description, created_by, link_sharing, share_token, share_token_hash, created_at, updated_at
`

type ProjectUpdateParams struct {
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	ID          string  `db:"id" json:"id"`
}

type ProjectUpdateRow struct {
	ID             string    `db:"id" json:"id"`
	TeamID         string    `db:"team_id" json:"team_id"`
	Name           string    `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	LinkSharing    string    `db:"link_sharing" json:"link_sharing"`
	ShareToken     *string   `db:"share_token" json:"share_token"`
	ShareTokenHash *string   `db:"share_token_hash" json:"share_token_hash"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ProjectUpdate(ctx context.Context, arg ProjectUpdateParams) (ProjectUpdateRow, error) {
	row := q.db.QueryRow(ctx, projectUpdate, arg.Name, arg.Description, arg.ID)
	var i ProjectUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.LinkSharing,
		&i.ShareToken,
		&i.ShareTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectUpdateLinkSharing = `-- name: ProjectUpdateLinkSharing :one
UPDATE projects
SET link_sharing    = $1,
    share_token     = $2,
    share_token_hash = $3,
    updated_at      = now()
WHERE id = $4
RETURNING id, team_id, name, description, created_by, link_sharing, share_token, share_token_hash, created_at, updated_at
`

type ProjectUpdateLinkSharingParams struct {
	LinkSharing    string  `db:"link_sharing" json:"link_sharing"`
	ShareToken     *string `db:"share_token" json:"share_token"`
	ShareTokenHash *string `db:"share_token_hash" json:"share_token_hash"`
	ID             string  `db:"id" json:"id"`
}

type ProjectUpdateLinkSharingRow struct {
	ID             string    `db:"id" json:"id"`
	TeamID         string    `db:"team_id" json:"team_id"`
	Name           string    `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	CreatedBy      string    `db:"created_by" json:"created_by"`
	LinkSharing    string    `db:"link_sharing" json:"link_sharing"`
	ShareToken     *string   `db:"share_token" json:"share_token"`
	ShareTokenHash *string   `db:"share_token_hash" json:"share_token_hash"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ProjectUpdateLinkSharing(ctx context.Context, arg ProjectUpdateLinkSharingParams) (ProjectUpdateLinkSharingRow, error) {
	row := q.db.QueryRow(ctx, projectUpdateLinkSharing,
		arg.LinkSharing,
		arg.ShareToken,
		arg.ShareTokenHash,
		arg.ID,
	)
	var i ProjectUpdateLinkSharingRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.LinkSharing,
		&i.ShareToken,
		&i.ShareTokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectVerifyAccess = `-- name: ProjectVerifyAccess :one
SELECT EXISTS(
  SELECT 1 FROM projects p
  INNER JOIN team_members tm ON tm.team_id = p.team_id AND tm.user_id = $2
  WHERE p.id = $1
)::boolean
`

type ProjectVerifyAccessParams struct {
	ID     string `db:"id" json:"id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) ProjectVerifyAccess(ctx context.Context, arg ProjectVerifyAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectVerifyAccess, arg.ID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
