// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package dbgen

import (
	"context"
	"time"
)

const sessionCreate = `-- name: SessionCreate :exec

INSERT INTO sessions (user_id, token, expires_at)
VALUES ($1, $2, $3)
`

type SessionCreateParams struct {
	UserID    string    `db:"user_id" json:"user_id"`
	Token     string    `db:"token" json:"token"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

// ============================================================================
// Session static queries (sqlc-generated)
// ============================================================================
func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) error {
	_, err := q.db.Exec(ctx, sessionCreate, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const sessionDeleteByToken = `-- name: SessionDeleteByToken :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) SessionDeleteByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, sessionDeleteByToken, token)
	return err
}

const sessionDeleteByUserID = `-- name: SessionDeleteByUserID :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) SessionDeleteByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, sessionDeleteByUserID, userID)
	return err
}

const sessionDeleteExpired = `-- name: SessionDeleteExpired :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) SessionDeleteExpired(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sessionDeleteExpired)
	return err
}

const sessionValidateToken = `-- name: SessionValidateToken :one
SELECT u.id, u.email, u.display_name, u.password_hash, u.created_at, u.updated_at
FROM sessions s
INNER JOIN users u ON s.user_id = u.id
WHERE s.token = $1 AND s.expires_at > now()
`

func (q *Queries) SessionValidateToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRow(ctx, sessionValidateToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
