// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suggestion.sql

package dbgen

import (
	"context"
	"time"
)

const suggestionCreate = `-- name: SuggestionCreate :one

INSERT INTO node_suggestions (
    project_id, node_id, field_name, proposed_value, current_value,
    rationale, evidence, proposed_by, agent_model, agent_session_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, status, created_at
`

type SuggestionCreateParams struct {
	ProjectID      string  `db:"project_id" json:"project_id"`
	NodeID         string  `db:"node_id" json:"node_id"`
	FieldName      string  `db:"field_name" json:"field_name"`
	ProposedValue  string  `db:"proposed_value" json:"proposed_value"`
	CurrentValue   *string `db:"current_value" json:"current_value"`
	Rationale      *string `db:"rationale" json:"rationale"`
	Evidence       []byte  `db:"evidence" json:"evidence"`
	ProposedBy     string  `db:"proposed_by" json:"proposed_by"`
	AgentModel     *string `db:"agent_model" json:"agent_model"`
	AgentSessionID *string `db:"agent_session_id" json:"agent_session_id"`
}

type SuggestionCreateRow struct {
	ID        string    `db:"id" json:"id"`
	Status    string    `db:"status" json:"status"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// ============================================================================
// NodeSuggestion static queries (sqlc-generated)
// ============================================================================
func (q *Queries) SuggestionCreate(ctx context.Context, arg SuggestionCreateParams) (SuggestionCreateRow, error) {
	row := q.db.QueryRow(ctx, suggestionCreate,
		arg.ProjectID,
		arg.NodeID,
		arg.FieldName,
		arg.ProposedValue,
		arg.CurrentValue,
		arg.Rationale,
		arg.Evidence,
		arg.ProposedBy,
		arg.AgentModel,
		arg.AgentSessionID,
	)
	var i SuggestionCreateRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const suggestionDecide = `-- name: SuggestionDecide :execrows
UPDATE node_suggestions
SET status = $1, decided_by = $2, decided_at = now(), decided_reason = $3
WHERE id = $4 AND status = 'pending'
`

type SuggestionDecideParams struct {
	Status        string  `db:"status" json:"status"`
	DecidedBy     *string `db:"decided_by" json:"decided_by"`
	DecidedReason *string `db:"decided_reason" json:"decided_reason"`
	ID            string  `db:"id" json:"id"`
}

func (q *Queries) SuggestionDecide(ctx context.Context, arg SuggestionDecideParams) (int64, error) {
	result, err := q.db.Exec(ctx, suggestionDecide,
		arg.Status,
		arg.DecidedBy,
		arg.DecidedReason,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suggestionFindByID = `-- name: SuggestionFindByID :one
SELECT id, project_id, node_id, field_name, proposed_value, current_value,
       rationale, evidence, proposed_by, agent_model, agent_session_id,
       status, decided_by, decided_at, decided_reason, created_at
FROM node_suggestions
WHERE id = $1
`

func (q *Queries) SuggestionFindByID(ctx context.Context, id string) (NodeSuggestion, error) {
	row := q.db.QueryRow(ctx, suggestionFindByID, id)
	var i NodeSuggestion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NodeID,
		&i.FieldName,
		&i.ProposedValue,
		&i.CurrentValue,
		&i.Rationale,
		&i.Evidence,
		&i.ProposedBy,
		&i.AgentModel,
		&i.AgentSessionID,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecidedReason,
		&i.CreatedAt,
	)
	return i, err
}

const suggestionListForNode = `-- name: SuggestionListForNode :many
SELECT id, project_id, node_id, field_name, proposed_value, current_value,
       rationale, evidence, proposed_by, agent_model, agent_session_id,
       status, decided_by, decided_at, decided_reason, created_at
FROM node_suggestions
WHERE node_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type SuggestionListForNodeParams struct {
	NodeID string `db:"node_id" json:"node_id"`
	Limit  int32  `db:"limit" json:"limit"`
}

func (q *Queries) SuggestionListForNode(ctx context.Context, arg SuggestionListForNodeParams) ([]NodeSuggestion, error) {
	rows, err := q.db.Query(ctx, suggestionListForNode, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeSuggestion{}
	for rows.Next() {
		var i NodeSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.NodeID,
			&i.FieldName,
			&i.ProposedValue,
			&i.CurrentValue,
			&i.Rationale,
			&i.Evidence,
			&i.ProposedBy,
			&i.AgentModel,
			&i.AgentSessionID,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecidedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestionListPending = `-- name: SuggestionListPending :many
SELECT id, project_id, node_id, field_name, proposed_value, current_value,
       rationale, evidence, proposed_by, agent_model, agent_session_id,
       status, decided_by, decided_at, decided_reason, created_at
FROM node_suggestions
WHERE project_id = $1 AND status = 'pending'
ORDER BY created_at DESC
LIMIT $2
`

type SuggestionListPendingParams struct {
	ProjectID string `db:"project_id" json:"project_id"`
	Limit     int32  `db:"limit" json:"limit"`
}

func (q *Queries) SuggestionListPending(ctx context.Context, arg SuggestionListPendingParams) ([]NodeSuggestion, error) {
	rows, err := q.db.Query(ctx, suggestionListPending, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeSuggestion{}
	for rows.Next() {
		var i NodeSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.NodeID,
			&i.FieldName,
			&i.ProposedValue,
			&i.CurrentValue,
			&i.Rationale,
			&i.Evidence,
			&i.ProposedBy,
			&i.AgentModel,
			&i.AgentSessionID,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecidedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestionSupersedePendingForNode = `-- name: SuggestionSupersedePendingForNode :exec
UPDATE node_suggestions
SET status = 'superseded', decided_at = now()
WHERE node_id = $1 AND field_name = $2 AND status = 'pending' AND id != $3
`

type SuggestionSupersedePendingForNodeParams struct {
	NodeID    string `db:"node_id" json:"node_id"`
	FieldName string `db:"field_name" json:"field_name"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) SuggestionSupersedePendingForNode(ctx context.Context, arg SuggestionSupersedePendingForNodeParams) error {
	_, err := q.db.Exec(ctx, suggestionSupersedePendingForNode, arg.NodeID, arg.FieldName, arg.ID)
	return err
}
