// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package dbgen

import (
	"context"
)

const teamCreate = `-- name: TeamCreate :one

INSERT INTO teams (name, slug, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, slug, created_by, created_at, updated_at
`

type TeamCreateParams struct {
	Name      string `db:"name" json:"name"`
	Slug      string `db:"slug" json:"slug"`
	CreatedBy string `db:"created_by" json:"created_by"`
}

// ============================================================================
// Team static queries (sqlc-generated)
//
// Dynamic / multi-statement queries kept as hand-written pgx in
// internal/repository/team.go:
//
//	GetMembers     — JOIN team_members + users into a flat struct
//	TransferOwnership — two-statement tx (demote old owner, promote new)
//
// ============================================================================
func (q *Queries) TeamCreate(ctx context.Context, arg TeamCreateParams) (Team, error) {
	row := q.db.QueryRow(ctx, teamCreate, arg.Name, arg.Slug, arg.CreatedBy)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const teamDelete = `-- name: TeamDelete :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) TeamDelete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, teamDelete, id)
	return err
}

const teamFindBySlug = `-- name: TeamFindBySlug :one
SELECT id, name, slug, created_by, created_at, updated_at
FROM teams
WHERE slug = $1
`

func (q *Queries) TeamFindBySlug(ctx context.Context, slug string) (Team, error) {
	row := q.db.QueryRow(ctx, teamFindBySlug, slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const teamFindByUserID = `-- name: TeamFindByUserID :many
SELECT t.id, t.name, t.slug, t.created_by, t.created_at, t.updated_at
FROM teams t
INNER JOIN team_members tm ON tm.team_id = t.id
WHERE tm.user_id = $1
`

func (q *Queries) TeamFindByUserID(ctx context.Context, userID string) ([]Team, error) {
	rows, err := q.db.Query(ctx, teamFindByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamMemberAdd = `-- name: TeamMemberAdd :exec
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
`

type TeamMemberAddParams struct {
	TeamID string `db:"team_id" json:"team_id"`
	UserID string `db:"user_id" json:"user_id"`
	Role   string `db:"role" json:"role"`
}

func (q *Queries) TeamMemberAdd(ctx context.Context, arg TeamMemberAddParams) error {
	_, err := q.db.Exec(ctx, teamMemberAdd, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const teamMemberCountByRole = `-- name: TeamMemberCountByRole :one
SELECT COUNT(*)::int FROM team_members WHERE team_id = $1 AND role = $2
`

type TeamMemberCountByRoleParams struct {
	TeamID string `db:"team_id" json:"team_id"`
	Role   string `db:"role" json:"role"`
}

func (q *Queries) TeamMemberCountByRole(ctx context.Context, arg TeamMemberCountByRoleParams) (int32, error) {
	row := q.db.QueryRow(ctx, teamMemberCountByRole, arg.TeamID, arg.Role)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const teamMemberExists = `-- name: TeamMemberExists :one
SELECT EXISTS(
  SELECT 1 FROM team_members WHERE team_id = $1 AND user_id = $2
)::boolean
`

type TeamMemberExistsParams struct {
	TeamID string `db:"team_id" json:"team_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) TeamMemberExists(ctx context.Context, arg TeamMemberExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, teamMemberExists, arg.TeamID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const teamMemberGetRole = `-- name: TeamMemberGetRole :one
SELECT role FROM team_members WHERE team_id = $1 AND user_id = $2
`

type TeamMemberGetRoleParams struct {
	TeamID string `db:"team_id" json:"team_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) TeamMemberGetRole(ctx context.Context, arg TeamMemberGetRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, teamMemberGetRole, arg.TeamID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const teamMemberRemove = `-- name: TeamMemberRemove :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type TeamMemberRemoveParams struct {
	TeamID string `db:"team_id" json:"team_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) TeamMemberRemove(ctx context.Context, arg TeamMemberRemoveParams) error {
	_, err := q.db.Exec(ctx, teamMemberRemove, arg.TeamID, arg.UserID)
	return err
}

const teamMemberUpdateRole = `-- name: TeamMemberUpdateRole :execrows
UPDATE team_members
SET role = $3
WHERE team_id = $1 AND user_id = $2
`

type TeamMemberUpdateRoleParams struct {
	TeamID string `db:"team_id" json:"team_id"`
	UserID string `db:"user_id" json:"user_id"`
	Role   string `db:"role" json:"role"`
}

func (q *Queries) TeamMemberUpdateRole(ctx context.Context, arg TeamMemberUpdateRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, teamMemberUpdateRole, arg.TeamID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const teamUpdate = `-- name: TeamUpdate :one
UPDATE teams
SET name = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, slug, created_by, created_at, updated_at
`

type TeamUpdateParams struct {
	Name string `db:"name" json:"name"`
	ID   string `db:"id" json:"id"`
}

func (q *Queries) TeamUpdate(ctx context.Context, arg TeamUpdateParams) (Team, error) {
	row := q.db.QueryRow(ctx, teamUpdate, arg.Name, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
