// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package dbgen

import (
	"context"
)

const userCreate = `-- name: UserCreate :one

INSERT INTO users (email, display_name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, display_name, password_hash, created_at, updated_at
`

type UserCreateParams struct {
	Email        string `db:"email" json:"email"`
	DisplayName  string `db:"display_name" json:"display_name"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

// ============================================================================
// User static queries (sqlc-generated)
// ============================================================================
func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRow(ctx, userCreate, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userFindByEmail = `-- name: UserFindByEmail :one
SELECT id, email, display_name, password_hash, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) UserFindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userFindByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userFindByID = `-- name: UserFindByID :one
SELECT id, email, display_name, password_hash, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) UserFindByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, userFindByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
